### ISSUE TITLE
Using a component inside <p>...</p> courses the element to render twice. 

### ISSUE THREAD

**Issue by emolr** [ionic-team/stencil#101]
```
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss'
})
export class MyName {

  @Prop() first: string;
  @Prop() last: string;

  render() {
    return (
      <p>
        <my-child name="Emil" />
      </p>
    );
  }
}

```

The above code outputs this in the DOM tree:

<img width="933" alt="screen shot 2017-08-23 at 12 48 59" src="https://user-images.githubusercontent.com/2789549/29612463-bb86ddf4-8801-11e7-893b-a51c7d1b2f4c.png">

<img width="235" alt="screen shot 2017-08-23 at 12 49 33" src="https://user-images.githubusercontent.com/2789549/29612425-8a8e5b14-8801-11e7-9e75-1d9af102a534.png">

I'm very amazed about this work, and thank you for the presentation at Polymer Summit 👍

**Comment by mlynch** [comment]
Hey @emolr, good seeing you last night and thanks for filing the issue :D

I've seen this before, what browser did this come from?

Any other details that might be different from the stock project we should look at?

**Comment by davidmpaz** [comment]
Hi @mlynch,

I am having same issue. I just follow the steps of the getting started guide. I did push my current hello world app here: https://github.com/davidmpaz/stencil-starter

thanks for this great project,

cheers

**Comment by jgw96** [comment]
Thanks for the repo @davidmpaz . I can reproduce this issue using your repo. If i change this https://github.com/davidmpaz/stencil-starter/blob/master/src/components/my-first-component/my-first-component.tsx#L14 to a `div` then i cannot reproduce it.

**Comment by davidmpaz** [comment]
Hi @jgw96,

thanks for answering. I did notice that with a `div` tag issue is gone. But I think the important part of this thread is to get to know the cause of this behavior.

From my user point of view having output displayed twice is not correct, I think we must know why is so, is it by design, is it really a bug, or a feature :) where lay the code for this and so on.

cheers

**Comment by adamdbradley** [comment]
Ok, dug into this more and I think it's a constraint of HTML itself, where a `<p>` paragraph tag cannot be nested inside of another `<p>` tag: https://www.sitepoint.com/community/t/p-inside-p/8402

I think it's because stencil is dynamically and asynchronously inserting `<p>` tags, the browser is more or less rearranging the elements to what's valid (at least that's my guess). 

We'll have to update our starts to NOT have `<p>` at the root.

**Comment by davidmpaz** [comment]
Hi @adamdbradley. thanks! for taking time to care of this. Is clear now.
