### ISSUE TITLE
Cannot clone this repo due to the permission issue

### ISSUE THREAD

**Issue by cloudhuang** [ionic-team/stencil#107]
As subject.

Here is the console log
 
```
➜  Desktop git clone git@github.com:ionic-team/stencil-starter my-app
Cloning into 'my-app'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Question:

1. do you have your ssh keys set up properly on GitHub? If not, cloning via ssh will not work
2. what happens if you go directly to the site: https://github.com/ionic-team/stencil-starter does that load? If that loads then you should have access.
3. if it does load, you can click the "Clone or Download" button and it will give you a few options, including using HTTPS. That may work better for you. The command from the command prompt will then be `git clone https://github.com/ionic-team/stencil-starter.git`

Thank you for using Ionic

**Comment by cloudhuang** [comment]
Thanks for the quick reply, yes, I downloaded it manually.

For the question 1 and 2, yes, I didn't setup the ssh publish keys for github, but I can visit the site indeed.

**Comment by mlynch** [comment]
Hi, try appending `.git` to the URL. We've updated the docs to reflect that and it should work. Cheers

**Comment by mlynch** [comment]
Actually try using the https URL:

`git clone https://github.com/ionic-team/stencil-starter.git my-app`
