### ISSUE TITLE
Stencil packages throw defineCustomElements is not a function in CodeSandbox or Stackblitz

### ISSUE THREAD

**Issue by jimthedev** [ionic-team/stencil#1071]
**Stencil version:**

```
 @stencil/core@0.11.2 or latest 0.12
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Currently stencil packages are not imported properly when used Codesandbox and Stackblitz. You can workaround by importing from package/dist/esm but IMO you shouldn't need to. Downloading the exact project from these editors and running locally works fine. My guess is there is something with their packager.

**Expected behavior:**
I would expect stencil packages to be able to be imported properly in these online editors since many people (including ionic) have examples in these editors.

**Steps to reproduce:**
Go to one of the sites, create a new project, try to use `import {defineCustomElements} from "split-me";` then use `defineCustomElements(window)` and you will get an error that defineCustomElements is not a function. Again, downloading the project locally does not have the same issue.

**Related code:**

[codesandbox example](https://codesandbox.io/s/wo9j867ln7) | [stackblitz example](https://stackblitz.com/edit/codesandbox-stenciljs-with-esm?file=index.js) are the examples with the workaround applied. Remove /dist/esm from the end of the import and you'll see the issue present itself.

**Other information:**

Obviously I suspect this is an issue with the packaging format Stencil is using and these editor's ability to import it so I've open an issue with one of them here to have visibility from the other side: https://github.com/CompuIves/codesandbox-client/issues/533#issuecomment-419445768

**Comment by jimthedev** [comment]
Per the linked codesandbox thread, it looks like both of these editors will do either esm or commonjs but prioritize commonjs over esm. They only do this if a main field is present in package.json. Since the stencil compiler seems to be creating an empty dist/index.js but aren't removing the main field, codesandbox ends up getting an empty file. So I guess the question is, is the bug that stencil should be putting something in dist/index.js or would it be better to simply remove the main property completely?

**Comment by edsilv** [comment]
This is blocking me from experimenting with https://github.com/emotion-js/emotion and Stencil. Their community prefers to use codesandbox.io to share examples.

**Comment by CompuIves** [comment]
Hey! Wanted to leave a comment on how the CodeSandbox bundler handles this currently:

If I remember correctly we honor an order of `browser` -> `main` -> `module`. The reason we favor `main` over `module` is that we can often transpile less. We transpile/bundle a sandbox when someone opens it, and we try to do as less transpiling as possible to make loading fast. With `module` we always need to transpile, because we need to parse the `export/import` statements.

It may be time to change this in CodeSandbox as the common bundler favor `module` over `main` nowadays, I'd have to check what the performance impact on loading would be. A quick 'fix' in the meantime would be to remove the `main` field from the `package.json`, if we don't detect a `main` field we move on to the `module` field.

**Comment by jimthedev** [comment]
Thanks everyone. If stencil makes a change to bundling then all current stencil packages would need to update and re-release a version. If @CompuIves makes the change then no one would (although there's other tradeoffs as you mentioned). Glad we're understanding this one more.

**Comment by adamdbradley** [comment]
Should be fixed in stencil one, thanks
