### ISSUE TITLE
Build fails when there are a lot of assets

### ISSUE THREAD

**Issue by jgroth** [ionic-team/stencil#1126]
I have a lot of assets in my project (5000+), and the Stencil build fails when trying to copy them to the build/dist folder

**Stencil version:**

```
 @stencil/core@0.13.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When having a lot of assets, the build fails with the following
```
Error: EMFILE, too many open files
```

**Expected behavior:**
The build should be able to handle any number of assets without failing

**Steps to reproduce:**
* Add a lot of files to `src/assets`
* Run `stencil build`
* Watch it fail

**Other information:**
My OS is Ubuntu 18.04. Increasing the number of open files permitted with `ulimit` might work if I increase it high enough, but will not work when there are even more assets than I have now.

My workaround at the moment is to have another script copying the assets over with https://github.com/AvianFlu/ncp after the stencil build has finished, but it's not a very clean solution and hard to get right when building in watch mode.

**Comment by adrianschmidt** [comment]
Further info:

I'm a teammate of @jgroth, so I'm running the same project, but on macOS 10.13.6 (High Sierra). For me, copying the Stencil way works, so there's some difference in either how the two OS:es performs the copying, or simply in the limit for number of open files.

This issue is actually a little nasty, in that it propagates to consumers of our project:

- Our project (Project A), is used as a dev-dependency in plugins also written with Stencil.
  (The project they plug-in to (Project B) provides Project A as a peer-dependency when running in production.)
- When running the dev-build for a plugin, we need to copy the Project A distribution into the dev-build target folder, and if we do that with Stencil's copy config, the same error occurs. So for the time being, the every plugin have to use the same type of workaround as @jgroth mentions above.
