### ISSUE TITLE
Ionicons and precacheAndRoute

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/stencil#1164]
**Stencil version:**
```
 @stencil/core@0.14.0-4 
```

**I'm submitting a:**
[X] bug report

**Current behavior:**
All SVG files in the `ionicons` project are being pre-cached by the sw.js

**Expected behavior:**
Ideally only the icons being used (somehow) would be cached.

**Steps to reproduce:**
The easiest way to reproduce this is with the `ionic-pwa-toolkit` project. If you run a build inside that and inspect the generated `sw.js` file you will see every SVG has been added to the precacheAndRoute list.

I am not directly including `ionicons` in my app (as neither is the `ionic-pwa-toolkit`) it is being included as a dependency of `@ionic/core`.

**Other information:**
Currently the `ionic-pwa-toolkit` pre-caches 725 files on first install, which seems excessive to me. In my app (which is based/seeded from `ionic-pwa-toolkit`) I'm looking to reduce this number. 697 of these files I believe are from `ionicons`.

**Comment by joewoodhouse** [comment]
Found that adding `globIgnores: ['**/svg/*.svg']` to be stencil.config.{tj}s will prevent them from being cached. Now probably just need to manually add each one I'm using back in using a custom `sw.js`.

**Comment by cjorasch** [comment]
The approach used for SVG files also has some other issues:
- Extra files to deploy if they are in www
- Hard to manually update sw.js or build scripts for icons used since no easy way to determine all icons.
- Hash based file versioning is not done on svg files so hard to cache or hard to update.

I think a better approach for icons would be to have the svg in importable js files.
```tsx
import { checkmarkIcon } from '@ionic/icons';
import { myIcon } from './my-icon';

<ion-icon icon={checkmarkIcon} />
<ion-icon icon={myIcon} />
```

Some benefits of this approach:
- Leverages standard module loading.  Inlined into component if used in one place, placed in chunk if shared.  Can be bundled via index file if desired.
- Fully synchronous rendering.
- Fewer resource requests.  Most ionic icons are very small and would benefit from being bundled with other code.
- Ability to cache forever and still update icons (via normal chunk hashes).
- Can easily use both ionic icons and other icons with svg available.
- Avoids pre-caching icons that you do not need.
- Can be rendered as pure function vs. component for better performance and memory.

More details: https://github.com/ionic-team/ionicons/issues/536
