### ISSUE TITLE
add react hook to stencil

### ISSUE THREAD

**Issue by mhamri** [ionic-team/stencil#1202]
I love what you guys are doing, it's something make me very excited. it's about combining all the good things out there. I have one suggestion

and a suggestion is to add hooks to stencil. it's a very exciting feature of the react and even though it's still in beta, but it can be a good addition to the tools set, what do you say?

**Comment by manucorporat** [comment]
We don't plans to make the runtime bigger adding more features. We are focus to make stencil faster, smaller and more compliant, rather than become a framework-like features.

However, we are internally experimenting with hooks, and it might lead to some external libraries in the future (like state-tunnel),but not part of the core of stencil for the moment.

**Comment by DarrylD** [comment]
I'm curious on how the experimenting is coming along.

Hooks for `state-tunnel` seems like a logical next step as it addresses the pain points of the current implementation of context.

**Comment by balupton** [comment]
the advantage of hooks  is that it offers a cleaner API to replace the current events, properties, internal state, and reactive data apis

**Comment by jdnichollsc** [comment]
Discussion here https://github.com/matthewp/haunted/issues/125#issuecomment-523476377

**Comment by loganvolkers** [comment]
Possible solution here: https://github.com/ionic-team/stencil/issues/1873#issuecomment-695057903
