### ISSUE TITLE
Using stenciljs without Typescript

### ISSUE THREAD

**Issue by stmoreau** [ionic-team/stencil#1244]
**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**
From my research I have found that stenciljs cannot be used without typescript,

**Expected behavior:**
I would like to be able to use stenciljs without using typescript.

**Other information:**
I know this might not be inline with the standards you have set, but it would be good to know.
Some background is that we are considering using stenciljs with my team but would like to have the option to use it without typescript as not all our members know it at the moment and we have to consider that as the development speed will drop significantly at first.

**Comment by matthew-dean** [comment]
> Some background is that we are considering using stenciljs with my team but would like to have the option to use it without typescript as not all our members know it at the moment and we have to consider that as the development speed will drop significantly at first.

I'm not on the Stencil team (just another person evaluating) but FWIW, the initial development speed may drop a bit, but just in my brief experience, trying both Stencil and TypeScript for the first time, with all the Intellisense offered using VSCode, it's been a waaay easier learning curve than learning React w/ vanilla JS. The fact it's using TypeScript has made it easier to learn Stencil, not harder, because so many hints are provided for decorators (also new to me) and method signatures.

**Comment by snaptopixel** [comment]
You can also lax all the typescript rules (via tsconfig.json) and essentially use vanilla js (although I wouldn't recommend it)

**Comment by thepian** [comment]
I'd also like to know if it's intended not to support plain JS. I'd consider that a non-starter.

**Comment by snaptopixel** [comment]
I don't think there is any intention of supporting plain JS, TypeScript brings so much to the table, especially with how Stencil leverages it (typed JSX, props, etc) it's worth the "trouble"

**Comment by jthoms1** [comment]
All AST work is done in Typescript.  So there is currently no way of writing stencil code without TS.

This would actually remove alot of the really nice features of Stencil.  We are pretty set on keeping TS a requirement.  Thanks!
