### ISSUE TITLE
Duplicate vdom elements will not re-render

### ISSUE THREAD

**Issue by tomsisk** [ionic-team/stencil#1451]
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When re-rendering a component with duplicate vdom elements, only the last element will update.

**Expected behavior:**

Every instance of the element should update.

**Steps to reproduce:**

I've made slight changes to the sample component. I've also put this in a repo, [here](https://github.com/tomsisk/stencil-vdom-duplicate-node). 

my-component.tsx:
```tsx
import { Component, Prop } from '@stencil/core';
import { format } from '../../utils/utils';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    const name = <b>{this.getText()}</b>;

    return <div>
      <div>Hello, World! I'm {name}</div>
      <div>I repeat, I'm {name}</div>
      <div>One last time, I'm {name}</div>
    </div>;
  }
}
```

index.html:
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>Stencil Component Starter</title>
  <script src="/build/mycomponent.js"></script>

</head>
<body>

  <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>

  <script>
    setTimeout(() => {
        document.querySelector('my-component').first = 'Not';
    }, 1000);
  </script>
</body>
</html>
```
After a second, the elements should re-render, replacing the first name with "Not", giving you:
```html
<div>
    <div>Hello, World! I'm <b>Not 'Don't call me a framework' JS</b></div>
    <div>I repeat, I'm <b>Not 'Don't call me a framework' JS</b></div>
    <div>One last time, I'm <b>Not 'Don't call me a framework' JS</b></div>
</div>
```

Instead you get:
```html
<div>
    <div>Hello, World! I'm <b>Stencil 'Don't call me a framework' JS</b></div>
    <div>I repeat, I'm <b>Stencil 'Don't call me a framework' JS</b></div>
    <div>One last time, I'm <b>Not 'Don't call me a framework' JS</b></div>
</div>
```

**Comment by tomsisk** [comment]
So pretty sure the problem is here: https://github.com/ionic-team/stencil/blob/9d790130e1b2ab26ade2ece71246168e79c07a8c/src/renderer/vdom/patch.ts#L361

This matches every time for text nodes, as they do not have a tag or key.

**Comment by adamdbradley** [comment]
After investigating this further we determined that sharing JSX nodes should be avoided, and we've updated our docs: https://stenciljs.com/docs/templating-jsx#avoid-shared-jsx-nodes

Each vnode that's created from JSX has its associated DOM node set as a property for faster lookup and improved renderer performance. However, when the vnode is shared and reused, this lookup gets incorrectly reset to the wrong DOM nodes. All things considered, we feel it's best for users to provide a factory function instead for this scenario, rather than sharing the same variable. Thanks for opening the issue, hope that helps out.

**Comment by dgibson666** [comment]
This was an informative thread because I'm running into similar issues. Can you shed some light on what the vkey represents though? It always appears undefined in the case we're troubleshooting, which means it's just comparing tag names all the time. Is there any other way to differentiate nodes so they update or force an update outside of the factory method? Just wondering. Thanks.

**Comment by beenotung** [comment]
As stencil use the vdom to cache the DOM object lookup, a favorable way is to use lambda:
```tsx
  render() {
    const text = this.getText()
    const name = () => <b>{text}</b>

    return <div>
      <div>Hello, World! I'm {name()}</div>
      <div>I repeat, I'm {name()}</div>
      <div>One last time, I'm {name()}</div>
    </div>;
  }
```
