### ISSUE TITLE
Cannot use multiple projects on the same page (1.0.0-alpha.8)

### ISSUE THREAD

**Issue by jgroth** [ionic-team/stencil#1459]
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.8 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When having multiple projects built with Stencil on the same page, the second project tries to load files from the first project with an invalid URL

**Expected behavior:**
It should be possible to have multiple projects built with Stencil on the same page without crashing

**Steps to reproduce:**

https://github.com/jgroth/multi-stencil

**Comment by adrianschmidt** [comment]
Some additional info:

We had this problem when we first started using Stencil to build plugins to our web app, but resolved it by setting the `resourceUrl` config parameter.

The issue was that the automatic resolver for resource url tried to get the url from the script tag that loaded the initial file, but when more than one such script tag was present on the page, it just grabbed the first one every time, resulting in only the first project loading correctly.

It seems like setting the `resourceUrl` parameter no longer has any effect.

**Comment by adrianschmidt** [comment]
This is related to #793 and #1456.

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
