### ISSUE TITLE
Support for link rel="stylesheet" instead of inline style tags

### ISSUE THREAD

**Issue by riovir** [ionic-team/stencil#1590]
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Stencil generated code relies on inline `<style>` tags to hook up CSS. Unfortunately, this practice conflicts with strict `Content Security Policy` headers that prohibit browsers from interpreting inline style tags.

**Expected behavior:**
Stencil would extract stylesheets into CSS files (at least for modern browsers, as IE11 doesn't support adherence to CPS headers anyway to my knowledge) and import them inside the shadow DOM via `<link rel="stylesheet" href="/[BASE_DIR]/my-component-[HASH].css">` This would avoid triggering  any security rule that would normally disable Stencil-made component styling.

**Steps to reproduce:**
Same as in issue: https://github.com/ionic-team/stencil/issues/496

**Other information:**
This is effectively a reopened form of the original #496 issue, now that Stencil `1.0.0` has been released, hoping for a solution.

**Comment by riovir** [comment]
Created accidentally

**Comment by manucorporat** [comment]
Unfortunately, this is not possible without a massive refactor. Components are lazy loaded and the `stylesheets` are inlined directly in order to reduce more network strips, in addition, adding links would introduce flickering when a component loads.

Fortunately, starting with Chrome, we are not using <style> tags anymore, but Constructable Stylesheets.

I would recommend to relax the CSP or avoid component-level styling, and place all your styles in a single global .css file, it will not be lazy loaded, but it will work

**Comment by riovir** [comment]
I appreciate your quick and direct answer. I relayed it back to our teams and unless someone strongly disagrees, I think this issue can be closed.

**Comment by dgibson666** [comment]
Is this why all of my custom CSS now shows as "user agent style sheet" in dev tools and I can't toggle these styles any longer? Is there any way around that?

**Comment by R0muald** [comment]
Hi @manucorporat , regarding to your point related to chrome using constructible styles, would that be possible to get more information about it? Does it mean that on chrome, the CSP would be satisfied and pass without "relaxing" the CSP rules? What about other browser?
