### ISSUE TITLE
stencil.core.d.ts missing on first build

### ISSUE THREAD

**Issue by alesgenova** [ionic-team/stencil#1705]
**Stencil version:**

```
 @stencil/core@1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The first time `npm run build` is executed (for example after removing the `dist` folder), the `dist/types/components.d.ts` will be missing.
After `npm run build` is run again, the file will be there.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by StefanNieuwenhuis** [comment]
I had the same problem while building stencil components and the problem lies in `package.json`.

```
{
    ...
    "types": "dist/types/index.d.ts",
    ...
}
```

`types` refers to `index.d.ts` and this one doesn't exist before building and therefore `components.d.ts` (in my case `stencil.core.d.ts`) is missing.

change `index.d.ts`  to `components.d.ts` to solve the problem.

```
{
    ...
    "types": "dist/types/components.d.ts",
    ...
}
```

**Comment by alesgenova** [comment]
@StefanNieuwenhuis  thank you for the hint, it seems to fix the problem I was having.
I wonder if it isn't more of a workaround though, since the stencil compiler should probably make sure that `index.d.ts` exists first.
But at least for the time being the build is fixed, so thank you so much again!

**Comment by gtranter** [comment]
My experience is that `stencil.core.d.ts` gets built _sometimes_. It is not a "fresh build" problem. Our build script removes `dist` entirely, so each build for us is "fresh". A pattern that has emerged is related to the order of the completion of two of Stencil's tasks:

```
[50:40.3]  bundling components finished in 16.12 s
[50:41.9]  type checking finished in 17.91 s
```
When bundling components completes before type checking, stencil.core.d.ts does not get added. This seems to happen most of the time. When the order of task completion is type checking before bundling components, it is added. 

Still using `index.d.ts` as the type file.

**Comment by gtranter** [comment]
The suggested workaround `"types": "dist/types/components.d.ts"` is proving to be a significant problem. With that, it is not possible to expose any non-component elements such as utility modules via the package import. 

For example, suppose `my-library` contains:
```
src/components.d.ts
src/components/...
src/global/index.ts (export * from './my-utility';)
src/global/my-utility.ts (export class MyUtility ... )
src/index.ts
```
where `src/index.ts` is:
```
export * from './components';
export * from './global';
```
Although anything in `global` is included in the package distribution, it is not consumable via a standard import for example `import { MyUtility } from 'my-library';` because the library's package.json defines `"types": "dist/types/components.d.ts"`, but the definition for `MyUtility` is not found there, it is found in `dist/types/index.d.ts`.

**Comment by splitinfinities** [comment]
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now. 

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it. 

Let me know if you need anything else!
