### ISSUE TITLE
@Method doesnt work as expected

### ISSUE THREAD

**Issue by maxim1006** [ionic-team/stencil#1790]
**Stencil version:**

```
"@stencil/core": "^1.0.7",
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

// in index.html

`<m-side-bar id="mSideBar"></m-side-bar>`

`<script>mSideBar.triggerOpen();</script>`

// in side-bar.tsx
```
@Method()
    async triggerOpen() {
        return this.open = true;
    }
```

// in browser console
mSideBar.triggerOpen is not a function

**Expected behavior:**

public method should work

**Steps to reproduce:**

see above

**Other information:**

**Comment by manucorporat** [comment]
The issue does not provide a repo case, but this is pretty much because the script runs before the web component is registered at all, you can use https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined to know when a web component is defined.

**Comment by bencody** [comment]
It would be nice if the Stencil documentation would show a full example of how (and when) methods can be used. 

In the past, one had to use `componentOnReady`, but that was changed in 1.0 I believe. Now, the documentation states:

> Developers can call methods before the implementation was downloaded without componentOnReady(), which queues the method calls and resolves after the component has finished loading.

This sounds like I can start using the web component right away, which unfortunately is not the case. It's not mentioned anywhere in the Stencil documentation that one still needs to wait for the component to be ready - now using `whenDefined` instead of `componentOnReady`.
