### ISSUE TITLE
HammerJS SwipeLeft & SwipeRight in StencilJS project

### ISSUE THREAD

**Issue by abritopach** [ionic-team/stencil#183]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
 └── @stencil/core@0.0.6-0 
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I cannot use HammerJS to perform and swiperight and swipeleft event.
**Steps to reproduce:**

1. Start new project
`git clone https://github.com/ionic-team/stencil-starter.git my-app
cd my-app
git remote rm origin
npm install`

2. Install Hammer library

`npm install hammerjs --save`

3. Import Hammer library
4. Added Hammer in collections (stencil.config.js)

`collections: [
    { name: '@stencil/router' },
    { name: 'hammerjs' }
  ]`

5. I get this error

`[ ERROR ]  stencil collection "hammerjs" is missing the "collection" key from its package.json`

**Related code:**

In tsx file

```
import * as hammerjs from 'hammerjs';
```

In stencil.config.js

`exports.config = {
  bundles: [
    { components: ['my-name'] }
  ],
  collections: [
    { name: '@stencil/router' },
    { name: 'hammerjs' }
  ]
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}`

Thanks!!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. Since this is more of a support question, I am going to close this  for now and ask that you join the [stencil-worldwide](https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM) slack and you can get some help there. Thanks!
