### ISSUE TITLE
defineCustomElements resourceUrl option not working

### ISSUE THREAD

**Issue by caseywoolley** [ionic-team/stencil#1846]
**Stencil version:**

```
@stencil/core@1.3.2
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Passing options to the "defineCustomElements" function for the "resourceUrl" 

**Expected behavior:**

Should change the resource url for lazy loaded stencil components.

**Steps to reproduce:**

**Related code:**

```tsx
defineCustomElements(window, { resourcesUrl: 'https://someUrl.com' });
```

**Other information:**

the resourceUrl option doesn't seem to have any effect on where stencil looks for it's resources. #903 mentioned that this was an undocumented feature.  Is that no longer the case?

**Comment by Krzyrok** [comment]
Any update on it?

**Comment by Krzyrok** [comment]
Tested on the @1.9.0-21 version and still does not work :/

**Comment by alvarocjunq** [comment]
Same for me, the parameter have no effect in the way that we load the component
I have a use case to loader from another domain (depending of some internal parameters)

This parameter will be really useful, today I'm doing a very bad "workaround" to solve it =/

**Comment by alicewriteswrongs** [comment]
Hey all, apologies that it took so long for something from the Stencil team to respond to this issue. I would like to get a better understanding of what exactly is going wrong so we can determine if this still needs to be fixed.

@alvarocjunq since you were still running into the issue relatively recently, is there any chance you could share a reproduction case that showcases the issue? Doing so will help the team diagnose the problem and work on a patch.

Sorry again for the delay in responding!

**Comment by alvarocjunq** [comment]
> @alvarocjunq since you were still running into the issue relatively recently, is there any chance you could share a reproduction case that showcases the issue? Doing so will help the team diagnose the problem and work on a patch.

Reproduce can be a bit difficult, cos it's necessary deploy the application somewhere and change the URL in the WebServer
Let me try to explain my use case:

1. I have a big Angular application that is deployed in `https://myserver.com/myapp/`
2. Inside of this big app, I have some WebComponents that retrieve the files (the javascript files created by Stencil in the lazy load output ) from another server `https://my-components-server/`
3. Looking to the loader generator of Stencil to be used in Angular, I've tried to use the property `resourcesUrl` to see if I can load the javascript related to that component, but didn't work =/

My workaround to this was get rid of the stencil loader (`defineCustomElements`) and load my components manually 😢 
Like:

```ts
        const source = this.location.prepareExternalUrl(`assets/config/my-component-mapping.json`);
        const subs = this.http.get<string[][]>(source)
           .pipe(switchMap(mappings =>
              forkJoin(mappings.forEach(m => new Observable(observer => {
                const scriptModule = this.doc.createElement('script');
                scriptModule.type = 'module';
                scriptModule.async = true;
                scriptModule.src = this.location.prepareExternalUrl(m[1]);
                this.doc.head.appendChild(scriptModule);
                scriptModule.onload = () => observer.next();
                scriptModule.onerror = (e) => observer.error({e, c: m[0], f: m[1]});
             }))
             )), finalize(() => { subs.unsubscribe(); })
          ).subscribe(
            () => { null; },
            (e) => console.error(`WebComponent '${e.c}@${e.f}' not loaded`, e.e)
        );
```
Where the file `my-component-mapping.json` have the name of all my components:

**Comment by alvarocjunq** [comment]
Hi @alicewriteswrongs 

Adding more info to the issue
I'm now transforming an Angular app that I have in my company in an Angular Element to be used inside of a Portal that we have
This Angular app uses two of our Stencil Components ❤️ 

When I build my Angular App in an Angular Element, the Angular/cli will create a specific bundle for each of my components (chunks with numbers like `918.js` or`455.js` because of the lazing load of Stencil for 2 components I have 4 chunks)

When I load my new Angular Element in this other application with their specific domain, I receive the error:

![image](https://user-images.githubusercontent.com/10416598/218975597-d5c30393-0498-4317-9012-abe9f7ed0b33.png)

The `defineCustomElements` method won't work to this case, because the file `918.js` is in another domain
I want to use the option `resourceUrl` to specify this domain of that portal and load the chunk correctly

**Comment by Apaltaratski** [comment]
@alvarocjunq i uses 
`import { setPublicPath } from 'systemjs-webpack-interop';`
and setting path using webpack `setPublicPath("https://my-components-server/");`

Note: if you are using global script be sure that is not contain requests by this url because declaration will be after global scripts

**Comment by christian-bromann** [comment]
@Apaltaratski thanks for providing more context to this issue. I agree this should be the way to set this up when using WebPack. If there is anyone still struggling with it, please let us know and if possible provide something reproducible so we can take a look and make Stencil better.
