### ISSUE TITLE
Feature Request: flag to ignore a Prop in generated docs

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1849]
**Stencil version:**
```
@stencil/core@1.3.2
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Request:**
I'd like a way to supress certain @Props from being generated in the auto-docs when using the [Auto-Generated docs.](https://stenciljs.com/docs/docs-readme#adding-custom-markdown-to-auto-generated-files). My use case is I want to set a default value for tabindex on the host element. I don't want this property to be added to the docs though because its a native property. Other use case is I generate an id for host if one is not provided. In both cases, I use @Prop to allow the end-user to override these attributes and only use a default if one isn't specified. But because these are native attributes, I don't want it to be part of the docs.

**Possible solution**:
`@Prop( { doc: false } ) tabindex = 0;`

**Other information:**
[Auto-Generated docs.](https://stenciljs.com/docs/docs-readme#adding-custom-markdown-to-auto-generated-files)

**Comment by stanley85** [comment]
I like the idea of having this feature, but not within the property config as sugested. Above the autogenerated content inside the *.md file could be a section that holds annotations to a property blacklist. This would be visible inside the docs but could be sorrounded by some usefull text.

`The following properties are excluded from the docs because they are default:
@undoc(['tag', 'title'])
`

Since every component is a unique new one there are no "default" properties attached to it am I wrong? I had props with "title" too, but chrome suggested to not have names of default properties within components. If your main component catches data to hand down to a JSX node with a default attribute this should be documented imho.

`
render() {
   <input tabindex={this.tabIndex} />
}
`

But I am not sure if chrome like camelcase notation of tabindex... there should be a reasonable name for this setting of your component.

**Comment by manucorporat** [comment]
This is already possible!!

```
/**
 * @internal 
 */
@Prop() notInDocs: string;
```

Ionic uses that a lot! you can apply this jsdoc pragma to Prop, Event, Method and the component itself!

**Comment by pr3tori4n** [comment]
@manucorporat sweet thanks.

**Comment by pr3tori4n** [comment]
@manucorporat I'm requesting this issue be re-open. Unfortunately, the @internal method has unintended side-effects outside of documentation. It also affects typescript compilation. If that prop is used by another Stencil component, a typescript error is thrown.

The use case I have is I want a Stencil component I'm writing that's using another Stencil component under the hood. I want to expose a prop for dog-fooding a component, but not have that prop be publicly documented. Using @internal prevents me from using that prop in another component I own.

**Comment by trazek** [comment]
Any word on this? I am also seeing the error thrown when other components attempt to use the `@internal` prop. Is this expected?

**Comment by trazek** [comment]
https://github.com/ionic-team/stencil/pull/2441/commits -- this PR adds another tag to exclude docs but does not effect build

**Comment by trazek** [comment]
@pr3tori4n I believe this fixes the issue -- https://github.com/ionic-team/stencil/pull/2447
