### ISSUE TITLE
Support React Hooks

### ISSUE THREAD

**Issue by KaboomFox** [ionic-team/stencil#1873]
Hooks are taking over the react community and it seems like people will be less likely to stencil if it is not supported.

I am hoping the Stencil will reconsider its position.

related to #1202

**Comment by manucorporat** [comment]
Stencil philosphy is to provide an API that matches 1-to-1 with web standards, class properties, HTML attributes, and DOM events... patterns that will last in time. 

We will not add hooks because it's trending today, that would hurt the future-proof design of stencil in some way.

Hooks are causing a react-lookin that developers will pay in the long term, simple functions now are shipping as react-only utilities that will hurt business by making all their code not reusable, this is something we are not up to do with stencil.

However, I am not against hooks per se, i can see how it helps in certain use cases (also makes the code more complex in others).

Adding hooks also means creating a new component model where there are not classes, and while this might look cool today it does not match the Web Component spec, where components are classes (and they will be until the end of the web).

**Comment by balupton** [comment]
The problem is react hooks are dramatically simpler to reason about and design and code, to the end-user programmer, than the previous technique of multiple class methods for doing one thing.

**Comment by valadas** [comment]
@manucorporat I could not agree more, this is why I love Stencil!

**Comment by shadowvzs** [comment]
> The problem is react hooks are dramatically simpler to reason about and design and code, to the end-user programmer, than the previous technique of multiple class methods for doing one thing.
> 
> Because of this, I use [lit-html](https://github.com/polymer/lit-html) with [haunted](https://github.com/matthewp/haunted) instead of stencil when I need web components.

other side example few state management lib like mobx make more simple then hook + prop propagation etc

**Comment by loganvolkers** [comment]
It turns out to be relatively early to connect [haunted](https://github.com/matthewp/haunted) to Stencil (like 15 lines of code)

```
import { Component, h } from '@stencil/core';
import { useState } from 'haunted';
import { useHook } from './stencil-hooks';

@Component({
  tag: 'example-hook',
})
export class ExampleHook {
  render = useHook(this, () => {
    const [count,setCount] = useState(0);

    return <div>Child is {count} <button onClick={()=>setCount(count+1}></button></div>;
  });
}
```

Source: https://gist.github.com/loganvolkers/6ba4335d0835d69a77b0b37b89589513

 - I agree with @manucorporat that this doesn't need to be part of the core library
 - Maybe it could be a package like `stencil-store` or `stencil-redux` (which is the inspiration for the stencil-hooks `forceUpdate` stuff)

**Comment by pvpd** [comment]
> The problem is react hooks are dramatically simpler to reason about and design and code, to the end-user programmer, than the previous technique of multiple class methods for doing one thing.
> 
> Because of this, I use [lit-html](https://github.com/polymer/lit-html) with [haunted](https://github.com/matthewp/haunted) instead of stencil when I need web components.

Functionnal programming. We really need this

**Comment by loganvolkers** [comment]
Version 0.0.4 of `@saasquatch/stencil-hooks` exists over here: https://github.com/saasquatch/stencil-hooks/tree/prerelease

It works and has tests, but will be getting a bunch more testing before it's fully production ready.

**Comment by pvpd** [comment]
Hooks in react are functionnal programming. Stencil will always be class based?

**Comment by adrm** [comment]
@pvpd Stencil will be class based as long as they keep their goal of aligning with the web platform, because the API for web components is an ES6 class, so that is a yes for the foreseeable future.

**Comment by marksyzm** [comment]
I thought web components and JavaScript objects were made from object constructors and that classes were recently created syntactic sugar, with inheritance being superfluous to the object being created?

**Comment by adrm** [comment]
In the general case yes, but AFAIK you need to use the `class` syntax to inherit from HTMLElement and create a new custom element. `class` is not implemented as a sugar syntax for prototypal inheritance although it works the same way in most cases.
