### ISSUE TITLE
Opt out of loadDocumentLinks in CSS Shim

### ISSUE THREAD

**Issue by abdulmhamid** [ionic-team/stencil#1881]
**Stencil version:**
```
 @stencil/core@<1.3.2>
```

**I'm submitting a:**
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
`loadDocumentLinks` currently fetches and parses through every stylesheet link with an href. We have several large CSS files that, while they declare CSS variables, we would like to keep from getting pulled into the DOM; we currently pull the CSS variables that we need into the DOM separately to allow the shim to work.

**Expected behavior:**
Use a named `data` attribute or other flag to ignore certain link tags.

**Related code:**
In the load-link-styles.ts file:
```tsx
export function loadDocumentLinks(doc: Document, globalScopes: CSSScope[]) {
  const promises: Promise<any>[] = [];

  const linkElms = doc.querySelectorAll('link[rel="stylesheet"][href]');
  for (let i = 0; i < linkElms.length; i++) {
    promises.push(addGlobalLink(doc, globalScopes, linkElms[i] as HTMLLinkElement));
  }
  return Promise.all(promises);
}
```

**Other information:**
This request is also related to https://github.com/ionic-team/stencil/issues/1880.

**Comment by manucorporat** [comment]
Can you submit a PR? how about [data-no-cssshim]?

**Comment by lotz** [comment]
We need something similar, but as we are integrating our Stencil components into many legacy pages, some options for top level opt-out of the CSS shim would be handy. Adding the `[data-no-cssshim]` attribute would be cumbersome and time consuming.

Specifically, we run into cross-origin issues with the `fetch` polyfill, as the CSS shim attempts to load and parse stylesheets that come from our CDN (different domain). This causes a bunch of console errors, which we'd like to avoid.

So a build configuration to either disable the CSS shim entirely (e.g. `disableCssShim`), or disable it for stylesheets loaded from a different domain (`disableCrossDomainCssShim`) would be useful. I'm open to other suggestions.

We are working around it right now with a runtime hack... to make it look like IE supports CSS vars, so that the shim does not get loaded.

```js
(function(win) {
    if (!win.CSS) {
        win.CSS = {
            supports: function(propName, value) {
                if (propName === 'color' && value === 'var(--c)') { return true; }
            }
        };
    }
})(window);
```

**Comment by lotz** [comment]
Hm, after investigating a bit more, it seems like Stencil already supports the `data-no-shim` attribute. This may work for us as the stylesheets aren't as widespread as we thought. Still, may be worth considering the above?

**Comment by abdulmhamid** [comment]
Fixed in https://github.com/ionic-team/stencil/pull/1901.
