### ISSUE TITLE
Name confliction with 'h'

### ISSUE THREAD

**Issue by beenotung** [ionic-team/stencil#1885]
**Stencil version:**

```
 @stencil/core@1.2.5
```

**I'm submitting a:**

[x] bug report

**Current behavior:**

Inside the render method, if there is a variable called `h`, it will override the `h` for tsx virtual dom construction.

**Expected behavior:**

The compiler should scan the code to determine a safe name of the `h` namespace for the JSX.

**Steps to reproduce:**

1. create a component
2. create a `render()` method inside the component
3. declare a variable named `h` inside the `render()` method, e.g. a number
4. load the component in a project
5. observe the console
You should see the error `TypeError: h is not a function`

**Related code:**
```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'virtual-scroll',
  styleUrl: 'virtual-scroll.css',
  scoped: true,
})
export class VirtualScroll {
  render() {
    let h = 123;
    return (
      <div>
        {h}
      </div>
    );
  }
}
```

**Other information:**

A workaround is to manually avoid name conflicting, but that will be a leak in the abstraction.

**Comment by beenotung** [comment]
It seems the `@Prop()` name cannot be `itemWidth` and `itemHeight` as well.
I tried to use them as number prop, got undefined, but if I rename to `w` and `h` then able to get the numeric value.

**Comment by manucorporat** [comment]
Can you open a new issue? second comment does not seem related.

Regarding the original commit, this is expected behaviour. Developers now manually import {h} which is the render function, this might look unconvenient, but it's how JSX works. 

`<div>` is just `h('div')` just syntax sugar. In React it gets replaced by `React.createComponent()`, in preact it's the same: https://preactjs.com/guide/getting-started

Just don't shadow `h`, there are tslint and eslint rules that can prevent variable shadowing.
In your case h is a number, but there are use cases where developers want to override the default render function h something else.
