### ISSUE TITLE
Component hydration errors with prerendering > 1.1.7

### ISSUE THREAD

**Issue by DominicBoettger** [ionic-team/stencil#1957]
**Stencil version:**
greater than 1.1.7
```
 @stencil/core@1.7.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When loading a html string with component information into a existing component i want that the sub component will be initialized too. 

**Expected behavior:**
Version 1.1.7 works and everything after does not work anymore. I am dynamically loading components into the body and in my case the stencil-router-link is missing the href when working with a version after 1.1.7. 

**Steps to reproduce:**
1. Checkout: https://github.com/INSPIRATIONlabs/stencil-seo-starter
2. npm run build -- --prerender
3. Prerendered result will not work as the current master uses 1.7.2
4. Downgrade stencil/core
5. npm install @stencil/core@1.1.7
6. npm run build -- --prerender
7. Result will have valid href attributes ( disabled javascript )

**Related code:**
https://github.com/INSPIRATIONlabs/stencil-seo-starter

**Other information:**

**Comment by tanner-reits** [comment]
Hi @DominicBoettger  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
