### ISSUE TITLE
How do I use this in IE 11?

### ISSUE THREAD

**Issue by trusktr** [ionic-team/stencil#197]
I'd like to use this in IE 11.

But, current transpilation tools (like Babel) will convert `super()` calls into something like `parentClass.call(this)`, which will break Stencil in new browsers. If we transpile for newer-than-IE11 browsers, then Stencil won't work in IE11.

Seems like this requires babel-preset-env along with Custom Elements v1 and `Reflect.construct` polyfills for older browsers.

Have you dealt with this?

**Comment by peterennis** [comment]
We do work for government agencies and many of them are stuck in MS land on old systems.
I have run into problems using ionic on IE11 and it was reported as not being supported.
This would be nice to have for broader reach of components but is way outside my current
competency level for implementation.
The idea makes sense give the push by ionic towards PWAs.
I would be happy to test.

**Comment by adamdbradley** [comment]
The dynamic loader decides which core file to use: one that uses class and super(), and one that uses the es5 way. Here's how the es5 setup is working: https://github.com/ionic-team/stencil/blob/master/src/client/core.es5.ts#L17-L20

Additionally, it is using the https://github.com/WebReflection/document-register-element polyfill which has been working great. There may be a new issues, but we've tested in the past with IE 11 and we haven't seen any problems.

As for `Ionic` supporting IE 11, it's more of a css issue than a custom element one. Because Ionic has traditionally been focused on mobile we haven't done much testing there, but that's all changing as we're working to support desktop further.
