### ISSUE TITLE
Stencil App doesn't work in IE11 in prod mode

### ISSUE THREAD

**Issue by ildar-icoosoft** [ionic-team/stencil#1974]
**Stencil version:**

```
 @stencil/core@1.5.2 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Stencil starter app doesn't work in IE11 in prod mode. There is a blank page with no errors in console.

**Expected behavior:**

It should work in IE11.

**Steps to reproduce:**

1. run `npm init stencil`
2. choose `ionic pwa`
3. enter project name. For example "test-stencil"
4. open the app directory `cd test-stencil`
5. run `npm run build`
6. run web server. I use "serve" npm utility.
 - run `npm i serve -g`
 - run `cd www`
 - run `serve -p 3333`
7. open `http://localhost:3333/`. Blank page is opened. Without errors in console.
![Снимок экрана 2019-10-28 в 11 20 21](https://user-images.githubusercontent.com/7842567/67656241-0d3b7100-f975-11e9-8953-673d4083a58e.png)

**Other information:**
In dev mode the app works fine. (If I use `npm run build -- --dev --es5` instead of `npm run build`)
IE version:
![Снимок экрана 2019-10-28 в 11 24 29](https://user-images.githubusercontent.com/7842567/67656432-9a7ec580-f975-11e9-85c2-f5fbe0b06a79.png)

**Comment by ildar-icoosoft** [comment]
@jpapillon It is not my index.html. It is Ionic starter application, I didn't change it
```
<head>
  <meta charset="utf-8">
  <title>PWA Toolkit</title>

  <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Welcome to the Ionic PWA Toolkit. You can use this starter to build fast PWAs using Ionic and Stencil!">
  <meta name="theme-color" content="#16161d">

  <meta name="format-detection" content="telephone=no">
  <meta name="msapplication-tap-highlight" content="no">

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-title" content="Ionic PWA">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <meta http-equiv="x-ua-compatible" content="IE=Edge">

  <script type="module" src="/build/app.esm.js"></script>
  <script nomodule src="/build/app.js"></script>

  <link href="/build/app.css" rel="stylesheet">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/icon/apple-touch-icon.png">
  <link rel="icon" type="image/x-icon" href="/assets/icon/favicon.ico">
  <link rel="manifest" href="/manifest.json">
</head>
```

**Comment by stanley85** [comment]
What happens if you do
`npm run build --prod --serve --watch`

**Comment by bubbleupdotnet** [comment]
@stanley85 if I do `npm run build --prod --serve --watch` then the app works in IE11. But I don't need the web server

**Comment by ildar-icoosoft** [comment]
@stanley85 if I do npm run build --prod --serve --watch then the app works in IE11. But I don't need the web server and watching for changes

**Comment by stanley85** [comment]
@ildar-icoosoft what happens if you do `npm run build --prod` instead of `npm run build` and use your own server? Maybe the IE polyfills are only applied if the prod flag is given.

**Comment by bubbleupdotnet** [comment]
@stanley85 I found out that if you use --watch flag then it will be dev build. Even if you use --prod flag. So `npm run build --prod --serve --watch` is a DEV build. If you use --watch flag, there is NO message in console: "Stencil is running in the development mode." and there is no service worker, but otherwise it's a DEV build. So `npm run build --prod --serve --watch` works in IE11 because it is a dev build. `npm run build --prod` doesn't work.

![PROD](https://user-images.githubusercontent.com/7842567/68921822-c08cce00-079b-11ea-97e3-12d2d93619ba.png)
![DEV](https://user-images.githubusercontent.com/7842567/68921824-c5ea1880-079b-11ea-8e1a-24906c1077d0.png)
![WATCH](https://user-images.githubusercontent.com/7842567/68921833-ca163600-079b-11ea-98ce-093b9dfe47f2.png)

**Comment by ildar-icoosoft** [comment]
@stanley85 I found out that if you use --watch flag then it will be dev build. Even if you use --prod flag. So `npm run build --prod --serve --watch` is a DEV build. If you use --watch flag, there is NO message in console: "Stencil is running in the development mode." and there is no service worker, but otherwise it's a DEV build. So `npm run build --prod --serve --watch` works in IE11 because it is a dev build. `npm run build --prod` doesn't work.

![PROD](https://user-images.githubusercontent.com/7842567/68921822-c08cce00-079b-11ea-97e3-12d2d93619ba.png)
![DEV](https://user-images.githubusercontent.com/7842567/68921824-c5ea1880-079b-11ea-8e1a-24906c1077d0.png)
![WATCH](https://user-images.githubusercontent.com/7842567/68921833-ca163600-079b-11ea-98ce-093b9dfe47f2.png)

**Comment by stanley85** [comment]
We are serving our index via apache, as soon as both files are included it should work. At least it does for us on 1.7.5

**Comment by erwingeiger** [comment]
I also have this problem. With v1.8.8 I get a white screen in IE11 after running `npm run build`

**Comment by sajTempler** [comment]
I noticed after deploying to CDN - paths for files for IE are wrong. Also happening for me @stencil/core 1.8.8

**Comment by max-scopp** [comment]
AFAIK stencil-starter doesn't support IE by default.
Just remove the module imports, add your polyfills, that's it.

**Comment by max-scopp** [comment]
@sajTempler Elaborate. Stencil doesn't do magic with paths.

**Comment by sajTempler** [comment]
@max-scopp 

Basically I was using stencil-component-starter (it has @stencil/core 1.8.8) - after running build and I ve put dist to my CDN

I took this approach from Stencil docs:
```
<script src=mycdndist/test-components.js></script>
```

So far so good, chrome is fine.

In IE though I ended up with trimmed urls (for subsequent requests)

```
https://mycdn.com/dist/p-e2e2e2ee2e2.js
```
instead of:
```
https://mycdn.com/dist/component/p-e2e2e2ee2e2.js
```

hence component not loading.

I switched to manually setting `src` like in starter template:
```
  <script type="module" src="https://mycdn.com/dist/stencil-starter-project-name.esm.js"></script>
  <script nomodule src="https://mycdn.com/dist/stencil-starter-project-name.js"></script>
```

after that IE is fine as well. Just pointing that script that adds script tags might be wrong
cheers

**Comment by va4ok** [comment]
I use `stencil build --docs --es5` and have a blank page in IE11 and IE Edge (not chronium). No errors, no warnings on page or console.
Looks like app not started because HOC has empty body
`<my-component></my-component>`
and in Chrome
`<my-component class="hydrated"><my-second-component class="hydrated">`

If i use `stencil build --docs --es5 --dev` it works ok. But it adds console warning about dev mode.

**Comment by tanner-reits** [comment]
Hey all  👋 

Sorry there was never a reply from the team on this, but I'm going to close out this issue as Stencil has officially deprecated support for IE11 (and some older versions of Edge) as a part of the v3 release (see [Stencil's browser support page](https://stenciljs.com/docs/browser-support)). But, please let us know if this behavior is experienced in any of our supported browsers.

Thanks!
