### ISSUE TITLE
buffer missing in "rollup-plugin-node-polyfills"

### ISSUE THREAD

**Issue by Francois-Belanger** [ionic-team/stencil#2041]
After importing Asyngular, I got the following error:

Node Polyfills Required
           For the import "buffer" to be bundled from
           node_modules/asyngular-client/lib/clientsocket.js, ensure the
           "rollup-plugin-node-polyfills" plugin is installed and added to the
           stencil config plugins. Please see the bundling docs for more
           information. Further information:
           https://stenciljs.com/docs/module-bundling

    "@stencil/core": "^1.5.2",

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

Using     "asyngular-client": "^6.2.0",

My stencil.config.ts:
```
import { Config } from '@stencil/core';
import nodePolyfills from 'rollup-plugin-node-polyfills';

// https://stenciljs.com/docs/config

export const config: Config = {
  outputTargets: [{
    type: 'www',
    serviceWorker: null
  }],
  globalScript: 'src/global/app.ts',
  globalStyle: 'src/global/app.css',
  plugins: [
    nodePolyfills(),
  ]
};

```
The "asyngular-client" is using 
const Buffer = require('buffer/').Buffer;

Is there a work around ?

Thanks

**Comment by Francois-Belanger** [comment]
Resolved by itself... Don't know why...

**Comment by Francois-Belanger** [comment]
Updated to @stencil/core v1.8.1... Same issue.

**Comment by Francois-Belanger** [comment]
Hi I was able to patch it.  Don't know if it's a good way.

in node_modules/rollup-plugin-node-polyfills/dist/index.js and index.mjs

added
    libs.set('buffer/', require.resolve('../polyfills/buffer-es6'));
under
    libs.set('buffer', require.resolve('../polyfills/buffer-es6'));

in both files.

Is this ok ?

Works.  Can do a PR.

Thanks

**Comment by lightxx** [comment]
This is still a thing in 2023 in stencil v3.0.1. how can this be? that's extremely frustrating to put it mildly.

**Comment by lightxx** [comment]
@Francois-Belanger have you ever found a solution that won't break updates?

**Comment by Francois-Belanger** [comment]
Hi, sorry I don't use that plug-in anymore.

**Comment by alicewriteswrongs** [comment]
@lightxx and @Francois-Belanger, sorry that no one from the Stencil team got back to you all about this issue for so long. I'm familiar with this part of the codebase (polyfilling node libs for browser use) and I know that it is a bit of a complicated beast!

@lightxx since you've been experiencing this issue recently, is there any chance you could share a minimal reproduction of the issue which will help us figure out how to address it?

Additionally, the `rollup-plugin-node-polyfills` project is not actively maintained, and polyfills for the node libs used by Stencil and its dependencies (like Rollup) are checked in to the Stencil repo directly now.
