### ISSUE TITLE
Props are undefined when e2e testing before passing them in with $eval

### ISSUE THREAD

**Issue by guidoknoll** [ionic-team/stencil#2053]
**Stencil version:**

```
 @stencil/core@1.8.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When e2e testing a component, it is suggested to pass in props with the page.$eval function. The problem with this is, that the component initializes already after `await page.setContent('<my-comp/>');`, so that the props are undefined at this moment and errors are thrown:
![image](https://user-images.githubusercontent.com/23310365/69976644-9c661680-1529-11ea-957a-c08765222a42.png)

**Expected behavior:**

Prop definition should be possible right before component initialization/loading in e2e tests. A tsx/jsx syntax like in the unit tests would be perfect:

```tsx
    const page = await newE2EPage({
       template: () => (
         <custom-select searchable={true} />
      )
    });
```

**Steps to reproduce:**

No steps to reproduce.

**Related code:**

```tsx
it('renders searchable list', async () => {
    const page = await newE2EPage();

    await page.setContent(`
      <custom-select/>
    `);

    await page.$eval('custom-select', (elm: any) => {
      elm.messages = {
        facets: {
            close: 'schlie\u00DFen',
            noResults: 'Leider keine Treffer gefunden.'
        }
      },
      elm.searchable = true;
    });

    await page.waitForChanges();
```

**Other information:**

**Comment by guidoknoll** [comment]
Yes, this is totally needed. When i try to write e2e tests, they always run in the same error: Props that are undefined because the component executes before props are set in set $eval method.

**Comment by christian-bromann** [comment]
Hi @guidoknoll  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
