### ISSUE TITLE
Invalid system.js build

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/stencil#2070]
**Stencil version:**
```
 @stencil/core@1.7.5
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When I run a build, one of the built system.js files seems to be invalid. Specifically the minified JS generated contains a call to a function `__extends_1` that does not exist. Trying to load this build in the browser causes errors.

**Expected behavior:**
System js built file should not contain errors.

**Steps to reproduce:**
Run a build

**Related code:**

[p-e1fea07b.system.txt](https://github.com/ionic-team/stencil/files/3939454/p-e1fea07b.system.txt)

search for __extends_1

**Other information:**
I assume this is some sort of rollup issue, but I've no experience with rollup so difficult for me to investigate myself.

**Comment by joewoodhouse** [comment]
Think this is probably the same issue as this?

https://github.com/ionic-team/stencil/pull/2013
https://github.com/microsoft/TypeScript/issues/35108

**Comment by christian-bromann** [comment]
Hi @joewoodhouse  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
