### ISSUE TITLE
Slot content has flash of unstyled before hydration

### ISSUE THREAD

**Issue by handfulglitter** [ionic-team/stencil#2101]
**Stencil version:**

```
 @stencil/core@1.8.1 (but seems to occur from version 1.0.1 and up)
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Components with slot content have a flash of unstyled content of the slot content before the component has a hydrated class on it. This happens on components that have and don't have shadow DOM. 

**Expected behavior:**
If the component isn't in a hydrated state yet, the slotted content in the component will be hidden.
**Steps to reproduce:**
- Clone the repo https://github.com/handfulglitter/stencil-issue
- `yarn` && `yarn start`
- Open the application on http://localhost:3333 with chrome. You can enable the cpu 4x slow down throttling to see the flash better. On every refresh you can see the flashing happening.

**Related code:**
In the stencil repo in bootstrap-lazy.ts some styling is being put in the data-styles of the html file where every component will have a visibility of hidden when the class doesn't have a hydrated class (lines 176-177). However it seems to be put inside the HTML after the slotted content is already loaded.

**Other information:**

**Comment by adamdbradley** [comment]
Ok I see what you mean. The challenge here is since Stencil 1.0, we're using `<script type="module">` which offers many benefits like being able to dynamically load [es modules](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/) with `import()`, being able to preload with `<link rel="modulepreload">` and using the browsers native implementation of module loading. 

However, one side effect is that `type="module"` is always asynchronous, meaning it won't block the main page until the script is done loading. Where is affects stencil v1 is that the hydrate css classes are not added to the `<head>` before the `<body>` and components are shown. So there's a moment where the html renders as fast as possible, then the es module executes and adds something like this to the head:

```
<style data-styles>
child-component, parent-component { visibility:hidden }
.hydrated { visibility:inherit }
</style>
``` 

With prerendering and SSR, stencil is able to add those styles to the index.html automatically. But for dynamically generated pages like your example, it has the problem from above.

The quickest solution is to manually add the `<style data-styles>` like the example to your index.html. But I'm happy to talk over some solutions in how we can make this easier for your use-case.

Thanks

**Comment by handfulglitter** [comment]
Thanks for your response! 
So you are saying that we should create our own styling with all components that make use of a slot? Isn't that something that should be the responsibility of stencil itself? 
I would like to hear the other solutions you have, since our components are used in several applications, and therefore applying extra stylesheets (which then would be there double since Stencil also makes these styles) manually wouldn't be ideal.

**Comment by adamdbradley** [comment]
Since it's an async script, there's a moment where the styles haven't applied yet. So the web page's light dom, such as the word `Text` within a component like `<ion-button>Text</ion-button>` will render immediately within the HTML, and when the esm script loads it hydrates the component. This would happen with any component using `esm`, stencil or not.

Stencil does add a script like this: ```<style data-styles>
child-component, parent-component { visibility:hidden }
.hydrated { visibility:inherit }
</style>``` Which helps prevent the flash in most cases, but there is still a situation where this can happen.

I'd recommend either adding a global stylesheet, or using just the `es5` build which would be synchronous.

**Comment by stephenbe** [comment]
There is also the option to add visibility hidden on the html directly.
```
html {
 visibility: hidden;
}
```

It comes with it's problems:
- If there is a JavaScript error on the page, you will see a blank page
- Users that have JavaScript disabled will see a blank page as well

Do you think this is a viable option @adamdbradley ?

**Comment by myWsq** [comment]
> There is also the option to add visibility hidden on the html directly.
> 
> ```
> html {
>  visibility: hidden;
> }
> ```
> 
> It comes with it's problems:
> 
> * If there is a JavaScript error on the page, you will see a blank page
> * Users that have JavaScript disabled will see a blank page as well
> 
> Do you think this is a viable option @adamdbradley ?

I think it's a good alternative. Maybe we should recover the visibility property of `html`  in `window.onerror` or `noscript` tag 😀

**Comment by stephenbe** [comment]
Oh great idea, my colleagues were mentioning that it might be too nuclear of a solution. With these fail-safes, it could be a better alternative.

**Comment by danfwdmotion** [comment]
I have a similar issue.

My use case is a little unorthodox, I use vuejs to create dynamic components in existing websites - this has it's problems as you have to clean your entire project of style or script tags, otherwise render multiple vue instances in key areas of the site.

I've decided to explore Stencil as it would appear to solve the issues I face with using vuejs, but a useful feature of vuejs is the v-cloak attribute - vuejs removes the v-cloak on load, you apply some styling to v-cloak to hide the content until the js loads.

Could something similar to this be implemented in Stencil?
