### ISSUE TITLE
missing "www folder" when "npm init stencil components" 

### ISSUE THREAD

**Issue by ClementPZ** [ionic-team/stencil#2163]
**Stencil version:**
@stencil/core@1.8.4
Mojave 10.14.6
NPM 6.13.14
Node 10.18.1

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When creating a components thru `npm init stencil components`: project is created BUT 
1. `npm start` do not launch the server
2. error on the browser ""
3. we realise there is the "www folder" missing in the project created
 
**Expected behavior:**
npm start launch server 
browser render boiler plate project

**Steps to reproduce:**
 npm init stencil component my-comps
cd my-comps
npm start

**Related code:**
the code is the stencil boiler plate for a components 

**Other information:**

**Comment by rwaskiewicz** [comment]
Hi @ClementPZ 👋 

I apologize that it took so long for someone on the team to get to this issue.

At this time, this is the intended behavior of the `create-stencil` CLI (`npm init stencil`). The `www` folder is created as a result of running `npm run build` or `npm start`, but doing so requires all of the project's dependencies to be installed first, which the CLI does not do (because we do not know what tooling folks want to use, npm, yarn, etc.).

Thanks again!

**Comment by ClementPZ** [comment]
Hello Ryan, 
It has been so much time that I had difficulties to reconnect with the issue !!! hahahha
Thanks anyways for answering !
Saludos from Mexico
C. 
----
Clément PZ 
Contactame en Whatsapp <https://wa.me/525528593354>
