### ISSUE TITLE
@Prop() does not handle null/undefined values correctly

### ISSUE THREAD

**Issue by aburkowsky9** [ionic-team/stencil#2180]
**Stencil version:**

```
 @stencil/core@1.9.0-13
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
It seems like the issue in this bug report has reared it's ugly head again - https://github.com/ionic-team/stencil/issues/252

**Expected behavior:**
See ticket above

**Steps to reproduce:**
See ticket above. I have seen this behavior in @Prop typed as Number and Boolean. I have not tested all cases.

**Comment by danyball** [comment]
Setting `@Prop() public value: string = ""` via JS `.value = undefined` also results in "undefined".

**Comment by christian-bromann** [comment]
You can define a component property as following:

```ts
@Prop() someProp?: string;
```

and if you use it like:

```ts
<my-other-component someProp={undefined} />
```

The prop is correctly typed as `undefined` and __not__ `"undefined"`. I am not sure if this issue has been resolved since it was posted but I am going to close this and am asking if you still encounter an issue, please raise a new issue so we can take a look.

Thank you for supporting Stencil!
