### ISSUE TITLE
CSS variables does not work in any browser when used in angular 

### ISSUE THREAD

**Issue by vinothbabu** [ionic-team/stencil#2202]
**Stencil version:**

```
 @stencil/core@1.9.0-18
```

CSS variables are defined in `src/global/variable.scss` is not getting affected when used in any frameworks like Angular or React. The components render fine, but the associated css variables declared in variable.scss does not boil down. 

This has no issue when you run the project as a standalone stencils project. It works fine in all the browsers.

**Comment by GerardvdStelt** [comment]
@vinothbabu I have the same issue and found this is for a long time already.

A few solutions mentioned online:
1. Add the css to your index.html
<link rel="stylesheet" href="/build/variable.css">

2. Through the sas plugin in stencil.config.ts:
plugins: [
    sass({
      injectGlobalPaths: ["src/global/variable.scss"]
    })
  ]

However in my case I have a CSS file in the global folder and just want to connect it to my component library with only *globalStyle: 'src/global/app.css'*. Because when going to production I would prefer not to manually add the css file but just the library.

**Comment by adamdbradley** [comment]
Global css will have to get imported by the project, which is the same as what Ionic does: 
https://ionicframework.com/docs/layout/global-stylesheets
https://ionicframework.com/docs/installation/cdn#css
