### ISSUE TITLE
[1.9.0] Tests failiing in lerna environment

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#2211]
**Stencil version:**

```
 @stencil/core@1.9.0-16 (and 1.8.x)
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Running `npm run test` throws `Unexpected token :` on the string `"version": "3.7.5"`. All info in the repo below.

**Expected behavior:**
Tests run successfully :-)

**Related code:**
https://github.com/bitflower/stencil-lerna-tests

**Comment by simonhaenisch** [comment]
Maybe related: https://github.com/facebook/jest/issues/8738.

**Comment by simonhaenisch** [comment]
https://github.com/ionic-team/stencil/blob/2911676947d5172965aa1d137bbfd049cd166cfa/src/compiler/transpile/transpile-module.ts#L58-L64

If you add a `console.log({ name, text })` there, you'll notice that there's five different files emitted:

- `my-component.e2e.js.map`
- `my-component.e2e.js`
- `my-component.e2e.d.ts.map`
- `my-component.e2e.d.ts`
- `tsconfig.tsbuildinfo`

The reason you got the error is because the last file's content is returned as the transpiled code of the module.

Changing it to the following would fix it:

```ts
if (name.endsWith('.js.map')) {
  results.map = text;
}
else if (name.endsWith('.js')) {
    results.code = text;
}
```

I'll make a PR for it but I'm not sure it's the correct solution. Maybe it would be better to prevent the program from emitting the unrelated files in the first place (if possible). The `tsbuildinfo` file is related to incremental builds I think?

**Comment by bitflower** [comment]
Thanks for the quick analysis @simonhaenisch !
