### ISSUE TITLE
Moving from Puppeteer to Playwright

### ISSUE THREAD

**Issue by dmartinjs** [ionic-team/stencil#2223]
**I'm submitting a:**

[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Test E2E with Puppeteer (only chromium engine)

**Expected behavior:**
Test with all Browser engines.

Did you plan to move from Puppeteer to Playwright ?

https://github.com/microsoft/playwright

**Comment by janrembold** [comment]
I honestly think the whole testing integration (currently done with an outdated version of puppeteer) should be removed from `@stencil/core` package. Don't get me wrong, the helpers build around web components are a nice thing but having it hardcoded inside Stencil just feels wrong to me.

Why is there a need to integrate an opinionated testing library anyways? Wouldn't it be much smoother to just install and configure it as it is actually intended? In the best case one could create a help library that offers special utilities for Stencil.

**Comment by klh** [comment]
Yeah i second removing the integration, but if tou keep it use playwright instead

**Comment by danyball** [comment]
Hi @rwaskiewicz - the issue got many upvotes. Whats your strategy to go on with this idea? Has "testing" a priority at your Backlog?

**Comment by rwaskiewicz** [comment]
Hey @danyball - this is something we're actively considering. While I can't promise a timeline, we're looking into ways to alleviate the painpoints of:

- Stencil keeping up with the current version of Puppeteer
- Stencil requiring the usage of Puppeteer
- Various libraries that need to be installed/how we communicate that to folks for new projects

**Comment by gustavo-mungarro** [comment]
Hi @rwaskiewicz 👋 - Is there an update regarding this topic?

**Comment by rwaskiewicz** [comment]
@gustavo-mungarro Not as this time, no. The team is prioritizing other work such as element internals, jest 29 support, and slot fixes at this time.

**Comment by gethari** [comment]
Hi @rwaskiewicz  👋 - Is there an update regarding this topic?

**Comment by rwaskiewicz** [comment]
> Is there an update regarding this topic?

The team is currently working on something to improve Puppeteer support that we hope to announce in the next month or so

**Comment by rwaskiewicz** [comment]
👋 Hey folks!

Yesterday, we released a library to help with using Playwright + Stencil :tada:  

While it’s still new, we’re curious to hear what you think! You can check it out at https://github.com/ionic-team/stencil-playwright, and it’s documentation is now live at https://stenciljs.com/docs/testing/playwright/overview.

We've done a little "rebrand" of sorts - moving forward, we're calling the existing Jest+Puppeteer Stencil testing infrastructure the "Stencil Test Runner". We plan on continuing to support that part of our offering in Stencil for the foreseeable future. However, we don't plan on changing the Stencil Test Runner to use Playwright instead of Puppeteer.

With that in mind, I’m going to close out this issue. If you have any feedback for our integration, we’d love to hear it in the new Stencil Playwright GitHub repo - Thanks!
