### ISSUE TITLE
compiler: provide warning/error if render() doesn't return anything

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#227]
**Stencil version:** 
```
 @stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
No errors from TS nor Stencil compiler. Consumer keeps scratching his head what went wrong.

**Expected behavior:**
Provide better DX providing error or warning message that render is not returning VNode

**Related code:**

Look ma, render doesn't return anything, but no errors occur

```ts
export class MyApp {
  render(){
    <div>
      <h1>My App</h1>
      <main>
        <my-datepicker/>
      </main>
    </div>
  }
}
```

**Comment by cjorasch** [comment]
If you use strong typing then you will get an error for this case.

`render(): JSX.Element` results in `[ts] A function whose declared type is neither 'void' nor 'any' must return a value.` if render does not return a value.

Note that in JSX it is important that you can return `null` , `undefined`, and `false` as valid render results to enabled things like `return this.initialized && <div>Hello</div>`.  You can also return arrays or strings.

**Comment by Hotell** [comment]
I'm very aware about how typescript and jsx works :) 

This error was not present before, because lack of proper types for ambient JSX namespace provided by stencil. Will re-try if it's fixed

**Comment by Hotell** [comment]
@cjorasch 
Your "solution" works only by explicitly annotating `render()` method which is kinda annoying and tools should help us to prevent bugs. That's why I've created this issue so stencil compiler will let user know that they are not returning anything :)

It can't be done by pure type definitions, because there is no type definition of base class ( as react uses for instance ) that could provide explicit typings for `render` method

**Comment by manucorporat** [comment]
@Hotell are you sure returning null is not actually a valid value for render()?

**Comment by Hotell** [comment]
null definitely is a valid return value, please read again what my "issue" is all about :) 

Thinking about it this could be mitigated by custom tslint rule that render needs to have `return`

**Comment by cjorasch** [comment]
Another possible approach would be to have a defined interface for components that can be used to enforce typings.  For example:

```tsx
// From @stencil/core or global?
interface StencilComponent {
  componentWillLoad?(): Promise<void> | void;
  componentDidLoad?(): void;
  // ... other lifecycle methods ...
  render(): JSX.Element;
}

// my-app.tsx
@Component({
  tag: 'my-app'
})
export class MyApp implements StencilComponent {
  render() {
    <div>
      <h1>My App</h1>
      <main>
        <my-datepicker />
      </main>
    </div>
  }
}
```

Some benefits
- Leverages TypeScript strengths.  Errors are reported in standard Problems panel vs in compile output.  Easier to find and fix.
- Requires render method to be implemented and enforces signature.  In this example it shows an error that there is no return value.
- Lifecycle methods get checked (although not that useful at this point since no args)
- `Go to definition` on interface to see all the lifecycle methods, etc.  Full syntax is easy to get to.
- Biggest downside is having to import the interface and reference it.

It seems like this issue might be related to a broader context of component type safety.  Components involve a complex blending of base ionic members, HTMLElement, etc. and it would be great to have an overall solution for type safety.

**Comment by Hotell** [comment]
right interface constraint should work for start.

> Biggest downside is having to import the interface and reference it.

This is not a downside at all, interface are gone after compile step so ZERO kb overhead, with latest IDE's editors it's just writing the interface and everything is gonna be imported for you :)
