### ISSUE TITLE
[Testing] Can't pass injected props manually in unit tests anymore

### ISSUE THREAD

**Issue by guidoknoll** [ionic-team/stencil#2310]
**Stencil version:**

```
 @stencil/core@1.11.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When unit testing my project it's no longer possible to manually pass injected props (via the state tunnel). Instead the default state from the config.provider.ts is used.

**Expected behavior:**

Injected props can be passed manually to the component as before.

**Steps to reproduce:**

Have a component with a injected prop:
```tsx
import Tunnel from '../../../../providers/config.provider';

@Component({
  tag: 'item-rating',
  shadow: false
})
export class ItemRating {

  @Prop() public showRatings: boolean;
  @Prop() public rating: number;

  public render() {
    ...
  }

}

Tunnel.injectProps(ItemRating, ['showRatings']);
```

Then unit test it:
```tsx
it.each([0, 0.5, 1, 3.2, 4.6])('should render item-rating component for average %s', async (av) => {
      const page = await newSpecPage({
        components: [ItemRating],
        template: () => (
            <item-rating rating={av} showRatings={true} />
        )
      });
      await page.waitForChanges();
      expect(page.root).toMatchSnapshot();
  });
```
When using console.log i see that showRatings is undefined because it has no default state in my config.provider.ts:

```tsx
export default createProviderConsumer<WidgetConfiguration>(
    {
      apiPath: '',
      dateFormat: '',
      messages: {},
    } as WidgetConfiguration,
    (subscribe, child) => (
      <context-consumer subscribe={subscribe} renderer={child} />
    )
);
```

**Other information:**

I use the @stencil/state-tunnel 1.0.1.
I mock it as described in https://github.com/ionic-team/stencil-state-tunnel/issues/4 with the mock of the state tunnel in `__mocks__/@stencil/state-tunnel`

**Comment by guidoknoll** [comment]
Ok, i solved this temporary with this workaround:
`if (!Build.isTesting) Tunnel.injectProps(CustomSelect, ['messages']);`

**Comment by samk-ayyagari** [comment]
@guidoknoll  Can you please elaborate how you did that ?

**Comment by christian-bromann** [comment]
Hi @guidoknoll  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
