### ISSUE TITLE
prerender issues with ion-grid, ion-loading

### ISSUE THREAD

**Issue by acoreyj** [ionic-team/stencil#2320]
**Stencil version:**

```
 @stencil/core@1.11.2 
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When prerendering flag is used some components have issues. 
For ion-grid you first see the content loaded full width
For ion-loading the dismiss does not work

**Example of basic site preloaded**: https://jolly-nobel-51a4e3.netlify.com/

- You see a flash of each column taking up the full width
- ion-loading never is dismissed even though it has a duration
- even running `await document.getElementsByTagName('ion-loading')[0].dismiss()` in the console returns false and does not dismiss the loading

**Example without preloading**: https://nervous-sammet-5dd49b.netlify.com/

- None of the above issues occur

**The code**:  https://bitbucket.org/acoreyj/prerendertest/src/master/

**Expected behavior:**

Preloading site should work the same as if it was not preloaded

**Steps to reproduce:**

Build using `--prod` and `--prerender` and deploy/serve (https://github.com/zeit/serve) the www directory.

See examples above,

**Related code:**
**The code**:  https://bitbucket.org/acoreyj/prerendertest/src/master/

**Other information:**

**Comment by rwaskiewicz** [comment]
Hey folks 👋 

I apologize it took so long for someone on the team to acknowledge this issue. In the time since this issue was originally posted, much has changed on both the Stencil and Ionic Framework side.  If you’re willing/able, would you be able to create a minimal reproduction case for the team with the latest version of Stencil + Ionic Framework? If not, I completely understand. Again, I apologize for the lack of response here
