### ISSUE TITLE
postcss plugins are running in weird order

### ISSUE THREAD

**Issue by marchbox** [ionic-team/stencil#2331]
**Stencil version:**

```
 @stencil/core@1.10.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I use Stencil’s postcss plugin to preprocess CSS files, with `stylelint` and `postcss-preset-env`. I have my stencil.config.ts file like this:

```ts
import {Config} from '@stencil/core';
import {postcss} from '@stencil/postcss';
import stylelint from 'stylelint';
import presetEnv from 'postcss-preset-env';
import reporter from 'postcss-reporter';

export const config: Config = {
  // ...

  plugins: [
    postcss({
      plugins: [
        stylelint(),
        presetEnv({...}),
        reporter({
          clearReportedMessages: true,
        }),
      ],
    });
  ],

  // ...
};
```

This worked fine until I updated Stencil version to 1.10.0 (verified with 1.9.0 and 1.9.2). In 1.10.0 and above, `stencil build --docs` still works fine, but when I run `stencil build --dev --watch --serve`, on CSS file updates, stylelint lints the transformed file (by postcss-preset-env) instead of the original file. This issue exists without `--dev`, too.

During my debugging process, it appears the following things run in this order:

1. stylelint lints the original files
2. postcss-preset-env transforms the original files
3. stylelint threw warnings/errors for the transformed files

**Expected behavior:**

Because `stylelint()` is added before `presetEnv()`, stylelint should always run before postcss-preset-env.

**Comment by rwaskiewicz** [comment]
👋 

I apologize that it took so long for a member of the Stencil team to respond to this issue. If you're interested/willing/able to provide a minimal reproduction case, we'd be happy to take a look to see if this is an issue in the latest version of Stencil, or the [Community Postcss Plugin](https://github.com/stencil-community/stencil-postcss/). Otherwise, I completely understand. Once again I apologize that this went unanswered for so long, and appreciate the time taken to putting up this issue/making Stencil better.
