### ISSUE TITLE
Error when testing properties on clicked nested components

### ISSUE THREAD

**Issue by mkay581** [ionic-team/stencil#2345]
**Stencil version:**

```
@stencil/core@1.12.3 
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
Test fails

**Expected behavior:**
Test succeeds

**Steps to reproduce:**

**Related code:**

```tsx
// my-cmp.spec.ts
import { newSpecPage } from '@stencil/core/testing';
import { MyCmp } from './my-cmp';

describe('MyCmp', () => {
  it('processes child clicks', async () => {
    const page = await newSpecPage({
      components: [MyCmp],
      html: '<my-cmp></my-cmp>',
    });
    const nestedCmp = page.root.shadowRoot.querySelector('my-nested-cmp');
    nestedCmp.click();
    await page.waitForChanges(); // just to see if this fixes 
    expect(page.root.result).toEqual('foo');
  });
});
```

<details>
<summary>my-nested-cmp.tsx</summary>

```tsx
import { h, Component, Prop } from '@stencil/core';

@Component({
  tag: 'my-nested-cmp',
})
export class MyNestedCmp {
  @Prop() foo = 'bar';

  render() {
    return <span></span>;
  }
}
```
</details>

<details>
<summary>my-cmp.tsx</summary>

```tsx
import { h, Component } from '@stencil/core';
import { MyNestedCmp } from './my-nested-cmp';

@Component({
  shadow: true,
  tag: 'my-cmp',
})
export class MyCmp {
  @Prop() result: string;

  private handleClick(ev: any) {
    const nestedCmp = ev.target as MyNestedCmp;
    this.result = nestedCmp.foo;
  }

  render() {
    return <my-nested-cmp onClick={this.handleClick}></my-nested-cmp>;
  }
}

```
</details>

**Other information:**

**Comment by cjorasch** [comment]
It looks like the click handler in my-cmp would not get the `this` context.

You could use: `onClick={ev => this.handleClick(ev)}` or set handleClick as an arrow function instance.

**Comment by mkay581** [comment]
Thanks for the response! 

The FAQs page says:

> With Stencil, the components appear as though they are React components and all properties get passed correctly including functions, objects, and arrays. The bindings also account for custom events by creating a prop called “on”. These allow React developers to interact with the Web Components as though they are React components.

I guess I thought that, based on that statement, Stencil components would work like React components so the same approaches would apply. React doesn't recommend doing `onClick={ev => this.handleClick(ev)}` due to performance issues that arise when a different callback is created each time the render is executed. Would that same performance hit be present with Stencil?

> set handleClick as an arrow function instance

Using arrow functions for class methods comes with [a lot of caveats and gotchas](https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1) and also has performance issues. Would these same performance issues still be present when using that approach with Stencil?

Our organization is buckling down on performance so want to make sure we won't suffer from performance issues with these approaches. Thanks for any information you can provide.

**Comment by cjorasch** [comment]
I don't think there is much unique to Stencil for these callbacks.  The options are pretty much the same for any JavaScript usage of class instance members.  The options are:
- onClick={this.handleClick}, and define handleClick as instance property
- onClick={ev => this.handleClick(ev)}
- onClick={this.handleClick.bind(this)}

In all of these cases a handleClick function instance is created for each component instance - it just depends on whether it is done in constructor or during render.

There are also some cases where you can get all the information you need from the call.  For example, you can often get the source HTMLElement from the event.  If the click handler only needs the element you do not need the this instance (and could even define the function outside of the class). 

The article does not mention it but I think the bigger issue with using arrow functions is all the closure data that come along with it.  This can add to memory usage in sometimes surprising ways.  Not only are you able to access `this` but also any other values in the scope.  Sometimes this is very useful (e.g. rendering a list of items and wanting to pass the item to a click handler) but sometimes it is not needed.

I am not sure exactly what was being measured in the article but it seems unlikely that instance properties are much different in performance because they still end up creating a function instance during the constructor.  It is possible it just measured the render time.  The time when there would be bigger differences is if you have a high number of renders relative to component constructor but in practice this is not that common and occurs over fairly long time intervals anyway.

Overall there are probably other areas with much more significant performance impacts.  For example, a single http call to load a required module takes over a million times as long.  Optimized code bundling is very hard but can have a big impact.

**Comment by mkay581** [comment]
There are other libraries that provide under-the-hood performance improvements that are better alternatives to those approaches to binding: Check out [Lit's events](https://lit-element.polymer-project.org/guide/events) for instance. Vue and Angular both have similar concepts to improve performance.

I tried changing to `onClick={(e) => this.handleClick(e)}` and that still doesn't work btw. 

Are you a part of the team that maintains Stencil?

**Comment by cjorasch** [comment]
Not a maintainer - just a user

Are you sure LitElement approach actually has better performance?  The simplified syntax may seem lighter but may still be creating function instances behind the scenes (similar to the bind approach).

**Comment by mkay581** [comment]
Lit doesnt use JSX and doesnt need to evaluate it so I'm pretty sure its more performant. I appreciate the responses but I'd like to keep the issue focused on the bug 😉. Happy to discuss performance in another thread though. Hopefully someone from the Stencil team can help us out with this.

**Comment by manucorporat** [comment]
You need to use:
```
 handleClick = (ev: any) => {
```
inteead of:
```
  private handleClick(ev: any) {
```
So it's an own property and this is automatically binded, not a stencil issue, https://gist.github.com/zcaceres/2a4ac91f9f42ec0ef9cd0d18e4e71262

**Comment by mkay581** [comment]
I've changed the `handleClick` to what you suggested and the following still produces an error.

```js
handleClick = (ev: any) => {
    const nestedCmp = ev.target as MyNestedCmp;
    this.result = nestedCmp.foo;
  };
```

Please reopen issue?

**Comment by mkay581** [comment]
@manucorporat ^

**Comment by manucorporat** [comment]
need to import both components:
```
    const page = await newSpecPage({
      components: [MyCmp, MyNestedCmp],
      html: '<my-cmp></my-cmp>',
    });
```

tested myself, this works:
```
describe('MyCmp', () => {
  it('processes child clicks', async () => {
    @Component({
      tag: 'my-nested-cmp',
    })
    class MyNestedCmp {
      @Prop() foo = 'foo';

      render() {
        return <span></span>;
      }
    }

    @Component({
      shadow: true,
      tag: 'my-cmp',
    })
    class MyCmp {
      @Prop() result: string;

      private handleClick = (ev: any) => {
        const nestedCmp = ev.target as MyNestedCmp;
        this.result = nestedCmp.foo;
      }

      render() {
        return <my-nested-cmp onClick={this.handleClick}></my-nested-cmp>;
      }
    }
    const page = await newSpecPage({
      components: [MyCmp, MyNestedCmp],
      html: '<my-cmp></my-cmp>',
    });
    const nestedCmp = page.root.shadowRoot.querySelector('my-nested-cmp');
    nestedCmp.click();
    await page.waitForChanges(); // just to see if this fixes
    expect(page.root.result).toEqual('foo');
  });
});
```

**Comment by mkay581** [comment]
Importing the nested component in the `components` property of object passed to `newSpecPage` fixed it. I can't seem to find anything on the [`newSpecPage` docs](https://stenciljs.com/docs/unit-testing#newspecpage) that mentions the nested elements must be explicitly added to `components` property to work in tests.  Can this be added to documentation?
