### ISSUE TITLE
Approve Screenshot Tests Individually In compare.html

### ISSUE THREAD

**Issue by bellindj** [ionic-team/stencil#2390]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

- We have about 150 screenshot tests.
- When we make changes that know will break some tests, we generally run the screenshot tests, look at compare.html to view changes are as expected, then rerun tests with the update flag to update master.json.
- There are 2 issues with having to accept all changes at once:
  1) Sometimes we may accidentally accept a failed test that wasn’t an expected change by missing it
  2) Rerunning with the update flag may actually produce a screenshot that is slightly different that the first run (we have seen this a few times where Stencil screenshots are not 100% consistent. It’s not related to animations, it simply has a hover in a weird place or a little extra padding at the top of the screenshot). We don’t actually know that the new batch will look like we want.

**Expected behavior:**

- Ideally, compare.html should be enhanced with an APPROVE button next to each changeset. The approve button would simply adjust master.json to hold a reference to the new screenshot.
- This would eliminate both issues we face and give us more confidence in the new base set of screenshots.

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by christian-bromann** [comment]
Hi @bellindj  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we are now supporting more frameworks to test Stencil components, e.g. [WebdriverIO](https://stenciljs.com/docs/testing/webdriverio/overview) or [Playwright](https://stenciljs.com/docs/testing/playwright/overview). For visual screenshot testing we recommend to use their visual capabilities as we are about to deprecate Stencils screenshot feature.

Please let me know if you have any questions!

Thank you for your understanding and support of StencilJS!
