### ISSUE TITLE
Feature request: type consistency across component props usage

### ISSUE THREAD

**Issue by fgandellini** [ionic-team/stencil#240]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.0.6-10
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I tried to set different props on a component, to see how each type was managed. I noticed a mismatch in behavior (serialize/deserialize), when a component is used inside another component or straight from the html. I dumped the sample component output (the code to print this is attached below): 

```
rendered from component:

        string: "test string"
        boolean: true
        number: 42
        arrayOfAny: [{"x":1},{"y":2},{"z":3}]
        arrayOfStrings: ["a","b","c"]
        arrayOfBooleans: [true,false]
        arrayOfNumbers: [4,5,6]
        arrayLiteralOfStrings: ["lit","eral"]
        arrayLiteralOfBooleans: [false,true]
        arrayLiteralOfNumbers: [7,8,9]
        arrayType: ["over","ride"]
        arrayOfUnionTypes: [1,"2",false]
        unionType: "ImAunionType"
      
rendered from html:

        string: "test string"
        boolean: true
        number: 42
        arrayOfAny: "[{\"x\":1},{\"y\":2},{\"z\":3}]"
        arrayOfStrings: "[\"a\", \"b\", \"c\"]"
        arrayOfBooleans: "[true, false]"
        arrayOfNumbers: "[4, 5, 6]"
        arrayLiteralOfStrings: "[\"lit\", \"eral\"]"
        arrayLiteralOfBooleans: "[false, true]"
        arrayLiteralOfNumbers: "[7, 8, 9]"
        arrayType: "[\"over\", \"ride\"]"
        arrayOfUnionTypes: "[1, \"2\",  false]"
        unionType: "ImAunionType"
```

**Expected behavior:**
I suppose that the expected output for the component would be the same in both cases:

```
rendered from component:

        string: "test string"
        boolean: true
        number: 42
        arrayOfAny: [{"x":1},{"y":2},{"z":3}]
        arrayOfStrings: ["a","b","c"]
        arrayOfBooleans: [true,false]
        arrayOfNumbers: [4,5,6]
        arrayLiteralOfStrings: ["lit","eral"]
        arrayLiteralOfBooleans: [false,true]
        arrayLiteralOfNumbers: [7,8,9]
        arrayType: ["over","ride"]
        arrayOfUnionTypes: [1,"2",false]
        unionType: "ImAunionType"
      
rendered from html:

        string: "test string"
        boolean: true
        number: 42
        arrayOfAny: [{"x":1},{"y":2},{"z":3}]
        arrayOfStrings: ["a","b","c"]
        arrayOfBooleans: [true,false]
        arrayOfNumbers: [4,5,6]
        arrayLiteralOfStrings: ["lit","eral"]
        arrayLiteralOfBooleans: [false,true]
        arrayLiteralOfNumbers: [7,8,9]
        arrayType: ["over","ride"]
        arrayOfUnionTypes: [1,"2",false]
        unionType: "ImAunionType"
```

**Steps to reproduce:**
I created a simple component with some props in order to check the behavior in each case. Then I rendered it using a wrapper component and directly from HTML. 

**Related code:**

```javascript
/* type-test.tsx */
import { Component, Prop } from '@stencil/core'

type UnionType = string | boolean | number

@Component({ tag: 'type-test' })
export class TypeTest {
  @Prop() string: string;
  @Prop() boolean: boolean;
  @Prop() number: number;  
  @Prop() arrayOfAny: Array<any>;
  @Prop() arrayOfStrings: Array<string>;
  @Prop() arrayOfBooleans: Array<boolean>;
  @Prop() arrayOfNumbers: Array<number>;
  @Prop() arrayLiteralOfStrings = ['x', 'y', 'z'];
  @Prop() arrayLiteralOfBooleans = [true, false];
  @Prop() arrayLiteralOfNumbers = [1, 2, 3];
  @Prop() arrayType: string[];
  @Prop() arrayOfUnionTypes: Array<UnionType>;
  @Prop() unionType: UnionType;

  render() {
    return (
      <pre>{`
        string: ${JSON.stringify(this.string)}
        boolean: ${JSON.stringify(this.boolean)}
        number: ${JSON.stringify(this.number)}
        arrayOfAny: ${JSON.stringify(this.arrayOfAny)}
        arrayOfStrings: ${JSON.stringify(this.arrayOfStrings)}
        arrayOfBooleans: ${JSON.stringify(this.arrayOfBooleans)}
        arrayOfNumbers: ${JSON.stringify(this.arrayOfNumbers)}
        arrayLiteralOfStrings: ${JSON.stringify(this.arrayLiteralOfStrings)}
        arrayLiteralOfBooleans: ${JSON.stringify(this.arrayLiteralOfBooleans)}
        arrayLiteralOfNumbers: ${JSON.stringify(this.arrayLiteralOfNumbers)}
        arrayType: ${JSON.stringify(this.arrayType)}
        arrayOfUnionTypes: ${JSON.stringify(this.arrayOfUnionTypes)}
        unionType: ${JSON.stringify(this.unionType)}
      `}</pre>
    )
  }
}
```

```javascript
/* type-test-wrapper.tsx */
import { Component } from '@stencil/core'

@Component({ tag: 'type-test-wrapper' })
export class TypeTestWrapper {
  render() {
    return (
      <div>
        rendered from component:
        <type-test
          string={'test string'}
          boolean={true}
          number={42}
          arrayOfAny={[{ x: 1 }, { y: 2 }, { z: 3 }]}
          arrayOfStrings={['a', 'b', 'c']}
          arrayOfBooleans={[true, false]}
          arrayOfNumbers={[4, 5, 6]}
          arrayLiteralOfStrings={['lit', 'eral']}
          arrayLiteralOfBooleans={[false, true]}
          arrayLiteralOfNumbers={[7, 8, 9]}
          arrayType={['over', 'ride']}
          arrayOfUnionTypes={[1, '2',  false]}
          unionType={'ImAunionType'}>
        </type-test>
      </div>
    )
  }
}
```

```html
/* index.html */
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <title>Stencil Starter App</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <meta name="theme-color" content="#16161d">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <script src="/build/app.js"></script>

  <link rel="apple-touch-icon" href="/assets/icon/icon.png">
  <link rel="icon" type="image/x-icon" href="/assets/icon/favicon.ico">
  <link rel="manifest" href="/manifest.json">
</head>
<body>

  <type-test-wrapper></type-test-wrapper>
  
  rendered from html:
  <type-test
    string="test string"
    boolean="true"
    number="42"
    array-of-any='[{"x":1},{"y":2},{"z":3}]'
    array-of-strings='["a", "b", "c"]'
    array-of-booleans='[true, false]'
    array-of-numbers='[4, 5, 6]'
    array-literal-of-strings='["lit", "eral"]'
    array-literal-of-booleans='[false, true]'
    array-literal-of-numbers='[7, 8, 9]'
    array-type='["over", "ride"]'
    array-of-union-types='[1, "2",  false]'
    union-type="ImAunionType">
  </type-test>

</body>
</html>
```

**Other information:**
I'm working to add the support for the `Array` type to the `Prop` decorator. If you want I can submit a PR. I would be glad if you want to give me some feedback about it! :)

**Comment by fgandellini** [comment]
Sorry guys, during my tests I also noticed a regression when using union types.
When I run the previous code with `@stencil/core@0.0.6-10`, I get:

```
rendered from component:

        ...
        unionType: "ImAunionType"
      
rendered from html:

        ...
        unionType: "ImAunionType"
```

If I run the same code with `@stencil/core v0.0.6-14`,  I get:

```
rendered from component:

        ...
        unionType: undefined
      
rendered from html:

        ...
        unionType: "ImAunionType"
```

Do you think I should open a separate issue for this?

**Comment by cjorasch** [comment]
When you are working in JSX you can specify actual values for the component properties.  These can include any JavaScript types.  It can also include things that can not be represented in a string (e.g. function references).  You will get some type safety from TypeScript (e.g. error when attempting to assign numeric value to boolean property) but not for complex types.

When you are working in HTML (vs. JSX) then you can only specify attributes as strings.  This is part of HTML and can not be changed.  For example, the `boolean` property is set to `"true"`.  Stencil does some primitive conversions internally so `boolean` and `number` attributes will be converted to native types.  It could potentially use `JSON.parse` for more complex objects but that would not necessarily result in the correct resulting data type for the component property.  For example, `array-of-strings="[1, 2, 3]"`.  Conversion could also be handled within the component (e.g. `arrayOfNumbers: number[] | string` and parsing strings) for cases when you want to allow usage from plain HTML.

I have run into this a few times when working on test pages and it can be confusing when you forget you are working HTML.  I have started using `body.tsx` as a root component so that I am always working in JSX.

It might be helpful for Stencil to log an error if you attempt to set a non primitive property value using an html attribute string.  That would make it easier to find the error.

**Comment by fgandellini** [comment]
Thanks for the quick answer @cjorasch!

Actually my current fix consists in
1. recognize that the current prop type is array
2. use `JSON.parse` to manage the js array inside the component
as for the `boolean` or `number` types.

So do you think this approach is overkill for this issue?

**Comment by cjorasch** [comment]
I think it depends on whether you are publishing a component for other people to use outside of a Stencil app or you are writing a component to use in your own Stencil app.  

If your component is being used from outside of a Stencil app then the only interface will be string based attributes so you need to design the component to handle string based property values.  If you need to have complex properties then using JSON.parse probably makes sense.

If you are creating a component used in a Stencil app (from JSX) then it is better to enforce strong typing rather than supporting flexible types and parsing strings.  In this case catching a string value as an error (vs. JSON.parse) seems like a better approach.

The Ionic folks would probably know better but my sense is that complex property values should be handled in one or two ways:
a) Log an error if attempting to specify an attribute value using a string that can not be converted to the declared type.
b) or perform JSON.parse conversion for string based attribute values if the declared property type does not support string.  

Some complications might be if the property is a union type that includes string, string enums, etc.  The Stencil meta data categorizes every property as String, Number, Boolean or Any.  If you declare a property as `string | number`, `'a' | 'b'`, or as an `enum` then Stencil handles it as Any.  This makes it hard to find type errors or know whether to convert.

React has a `PropTypes` framework that allows more complex type specifications.

Ideally Stencil would provide strong type checking for JSX files rather than lumping most things into `any`.  It seems a shame to only get the great TypeScript strong typing benefits within a component and not when using a component in JSX.

**Comment by fgandellini** [comment]
Got it @cjorasch, thanks again!
Let's see what Ionic guys think about this, anyway feel free to close this issue.

**Comment by jthoms1** [comment]
Thanks @cjorasch, that is a great explanation! I think what is trying to be accomplished here is to work around the limitations of HTML.  We do some type inference such as numbers and booleans but I would say that your best approach would be to stick to JS to set complex values. ie (arrays or objects).

```html
/* index.html */
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <title>Stencil Starter App</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <meta name="theme-color" content="#16161d">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <script src="/build/app.js"></script>
  <script>
    window.addEventListener('load', () => {
      const el = document.querySelector('type-test-wrapper');
      el.string = "test string";
      el.boolean = true;
      el.number = 42;
      el['array-of-any'] = [{"x":1},{"y":2},{"z":3}];
      el['array-of-strings'] = ["a", "b", "c"];
      ...
    });
  </script>

  <link rel="apple-touch-icon" href="/assets/icon/icon.png">
  <link rel="icon" type="image/x-icon" href="/assets/icon/favicon.ico">
  <link rel="manifest" href="/manifest.json">
</head>
<body>

  <type-test-wrapper></type-test-wrapper>
  
  rendered from html:
  <type-test></type-test>
</body>
</html>
```

**Comment by fgandellini** [comment]
WOW! Thanks @jthoms1, that is a great example of how to manage it!
Thanks for all your hard work! :muscle: Stencil is very cool! :sunglasses:

See you on Slack guys!

**Comment by trusktr** [comment]
Have you all looked at how SkateJS (and LitElement which is heavily inspired from Skate) handle dynamic types for attributes? They both allow the component author to specify, for any given prop, how JS values are serialized/deserialized to/from attribute strings.

The gist of it (not exactly Skate or LitElement, but you get the idea):

```js
class MyEl extends Element {
  props = {
    foo: { deserialize: string => SomeComplexType.from(string), serialize: (value) => value.toString() }
  }

  render() { return <div>this.foo</div> }
}

customElements.define('my-el', MyEl)
```

where `SomeComplexType`'s `from(string)` method knowns how to initialize a new instance of `SomeComplexType`, and `SomeComplexType.prototype.toString` knows how to convert to a string of the same format as the one passed into `from()`.
