### ISSUE TITLE
@Watch decorator methods should be tiggered before first render

### ISSUE THREAD

**Issue by milottit** [ionic-team/stencil#2451]
**Stencil version:**
```
 @stencil/core v1.13.0
```

**I'm submitting a:**

[x] bug report
[] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

@Watch decorator methods is not called before the first render

**Expected behavior:**

@Watch decorator methods should be called before the first render

**Related code:**

Let's define a simple component:

```tsx
import { Component, Host, h, Prop, Watch } from '@stencil/core';

@Component({
    tag: 'el-test'
})
export class ElTest {
    @Prop() prop: string;

    @Watch('prop')
    watch(newValue: any, _, propName: string) {
        console.log({ propName, newValue });
    }

    render() {
        return (<Host></Host>);
    }
}
```

Now let's instantiate it and see the output:

```html
<el-test id="test" prop="a little test"></el-test>
```

Looking at the console, one can observe that no output is displayed. If we want the @Watch method to be called before the first render, we have to call it manually in `componentWillLoad`.

**Comment by trazek** [comment]
The docs say that it won't fire on initial load - https://stenciljs.com/docs/reactive-data#watch-decorator

Maybe this can be considered a feature request but not sure about a bug?

**Comment by manucorporat** [comment]
This is the expected behaviour, you should handle this initial load in componentWillLoad too. While the other behaviour might make sense for your, it does not for everyone, imagine emitting an "change" event, you would not want this to be triggered at first.

Changing this behaviour would require a full doccument reviewing all the advantages and disadvantages and even thought it would break all stencil apps, unfortunately it's not something wee change change at this point. But there are workarounds.

**Comment by milottit** [comment]
@manucorporat Ok I get it. But maybe an option in the @Watch decorator to opt-in for the function to be triggered during initial load. Like that, it is backward compatible and there is no need to discuss about pros and cons.

I see you have a little tendency to close issues before even considering an exchange. It would be nice to discuss and then eventually close the issue if it is relevant.
