### ISSUE TITLE
Full local-machine file path locations in d.ts file output

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#2470]
**Stencil version:**

```
 @stencil/core@1.13.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The output `components.d.ts` file occasionally and rather inconsistently contains the full local file path for an unresolved `import()` created during a build. For example:

Most builds:
```ts
interface SomeComponentInterface {
   "getThingy": () => Promise<Thingy>;
}
```
... sometimes comes out as:
```ts
interface SomeComponentInterface {
  "getThingy": () => Promise<{ thingy: import("C:/full/path/to/thingy/api").ThingyAPI }>;
}
```

**Expected behavior:**

Compiling does not include path information from the machine its built on and all TS APIs are resolved.

**Steps to reproduce:**

It is completely random when it happens but I find out when developer attempt to use the package I created and the path cannot be found. If I build the package 100 times, I may run into this 3 times.

**Related code:**

```tsx
// none
```

**Other information:**

This is being compiled on a windows 10 machine which may be relevant to the output or resolution. This has happened on and off since 1.0.0 so I have no idea where to begin.

**Comment by tanner-reits** [comment]
Hi @cary-smith  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
