### ISSUE TITLE
Typescript dependency mismatch causes build issues

### ISSUE THREAD

**Issue by markcellus** [ionic-team/stencil#2477]
We are using stencil 1.12 which uses its [own `3.8.3` version of TypeScript](https://github.com/ionic-team/stencil/blob/v1.12.7/package.json#L52). But we are using a higher version of TypeScript (`3.9.3`) in our project. The mismatch seems to be causing inconsistencies in Stencil's build process. `npm ls typescript` produces

```
├─┬ @stencil/core@1.12.7
│ └── typescript@3.8.3 
└── typescript@3.9.3
```

We are not yet ready to upgrade Stencil because that is also causing issues but we are fine with using our own upgraded version of TypeScript.

**Stencil version:**

```
 @stencil/core@1.12.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The build fails due to a TS error raised in typescript 3.9.3 version. But any subsequent build does not fail on any TS error because stencil uses the 3.8.3 version that doesn't raise the error.

**Expected behavior:**
All builds to fail consistently on the TS error.

**Steps to reproduce:**
In a Stencil 1.12 repo deliberately add a TS error in a component spec file that is raised in typescript `3.9`, upgrade TypeScript to latest version `3.9.3`. Run the stencil build.

**Comment by mkay581** [comment]
I believe the easiest way to fix this issue and potential future ones is to just make `typescript` a peer dependency. Is that a possibility?

**Comment by rwaskiewicz** [comment]
Hey @markcellus 👋 

I apologize it took so long for someone on the team to acknowledge this ticket. 

In the time since this issue was initially reported, Stencil has changed how it uses TypeScript. Stencil now embeds a version of TypeScript in the Stencil compiler to ensure compatibility between the TypeScript APIs Stencil uses, and the code folks write. This is a stance the previous Stencil team has taken that the current team has decided to continue to support.

Today, running `npm ls typescript` in a project that does not explicitly install typescript results in the following:
```
npm ls typescript
simple-proj@0.0.1 
└── (empty)
```

I'm going to close this issue, but want to apologize again for how long it took for someone to acknowledge this issue. Thanks again!
