### ISSUE TITLE
Disable "node polyfills required" plugin

### ISSUE THREAD

**Issue by cramshaw** [ionic-team/stencil#2490]
**Stencil version:**

```
 @stencil/core@1.10.0
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I have a stencil app which runs in electron. As such, I have access to node builtins, and require this access. I've been pinned to v1.9.2 for some time, because newer builds have broken this.

At the moment I get around the node-polyfills warning by 'requiring' the module that contains all the builtin calls. I realise this is far from ideal, but deadlines etc.

On mac, I can run and build fine, but on Windows v1.10.0 throws the 
```
[ ERROR ]  Node Polyfills Required
           For the import "http" to be bundled from
            http?commonjs-external, ensure the
           "rollup-plugin-node-polyfills" plugin is installed
           and added to the stencil config plugins. Please see
           the bundling docs for more information. Further
           information:
           https://stenciljs.com/docs/module-bundling
```

**Expected behavior:**

I would like to be able to turn off the [plugin-helper](https://github.com/ionic-team/stencil/blob/master/src/compiler/bundle/plugin-helper.ts) which throws this error. The dev server actually builds and runs despite the error, (and on hot reload builds successfully) but the error is stopping me from being able to make a prod build.

**Steps to reproduce:**

A stencil app running inside electron which imports a node builtin, such as fs. A minimum example is not trivial but I could provide if needed.

I'm open to any alternative solutions, I have tried newer versions of stencil, but run into further issues.I seem able to get as high as 1.13.0 before those occur, but it's from 1.9.2 to 1.10 that this starts happening, I can't see anything in the changelog to suggest why. 

Thanks,

Chris

**Comment by christian-bromann** [comment]
Hi @cramshaw  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
