### ISSUE TITLE
Component name ending with "test" (e.g. "latest") will throw test error

### ISSUE THREAD

**Issue by fyyyyy** [ionic-team/stencil#2496]
**Stencil version:**

```
    "@stencil/core": "^1.12.2"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
tests fail

**Expected behavior:**
tests pass

**Steps to reproduce:**
generate a new stencil component via npm init stencil 
rename component to e.g. "latest.tsx"
run stencil test
    "test": "stencil test --spec --e2e"

 jest args: --e2e --spec --max-workers=8
 FAIL  src/components/latest/latest.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

**Comment by DrMabuse23** [comment]
any news here ?

**Comment by tanner-reits** [comment]
@fyyyyy @DrMabuse23 Sorry for this issue sitting unanswered for so long!

If either of you are still experiencing this issue with a recent version of Stencil, could you please update to issue to include a minimum reproduction repo? That would help our team dramatically as we start sifting through our un-triaged issues. Otherwise, we'll look to close this out in the near future. Thanks in advance!

**Comment by musangowope** [comment]
I'm experiencing this something similar
**Stencil version**
```
"@stencil/core": "2.17.4",
```

Current behavior:
tests fail

Expected behavior:
tests pass

Steps to reproduce:
In the terminal run  
`stencil test --spec --e2e`
The terminal will output
```
jest args: --e2e --spec --max-workers=8
```
Then get to this error:

Your test suite must contain at least one test.
```
 src/components/toc-item/toc-item.e2e.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
```

**Further observations:**
If I run `stencil test --e2e`, all my end-to-end tests pass.
But when I run `stencil test --spec --e2e`, that error will happen

**Comment by rwaskiewicz** [comment]
@musangowope  can you do us a favor and create a minimal reproduction case & a new issue for the team to take a look at? Thanks!
