### ISSUE TITLE
bug: size of bundle significantly increased

### ISSUE THREAD

**Issue by sshrshnv** [ionic-team/stencil#2506]
# Bug Report

**Ionic version:**

[x] **5.1.1**

**Current behavior:**

Significantly increased the size of the bundle since 5.0.6 version: 19.9kB instead 8.3kB.

**Expected behavior:**

The bundle size remains the same.

**Steps to reproduce:**

![ionic](https://user-images.githubusercontent.com/7159528/84203851-c9841a80-aab2-11ea-9d11-9ff353227d87.png)

**Comment by rwaskiewicz** [comment]
👋 

Hey there! I apologize that nobody from the Stencil team has acknowledged this ticket since it was transferred.

Unfortunately, it predates everyone on the current team. Since it's creation, three new major versions of Stencil have been released, and multiple major versions of the Ionic Framework as well. At this time, there's no great actionable item here for us to tackle with respect to Ionic Framework v5 and the version of Stencil it used. As a result, I'm going to close this ticket.

However, I have created an internal ticket for the team to look into tracking the size of the compiler over time/with new releases. More on that to come!
