### ISSUE TITLE
Angular and styles not rendering

### ISSUE THREAD

**Issue by bfleischer-alti** [ionic-team/stencil#2513]
```
 Version @stencil/core@1.14.0
 Version angular@9.1.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The StencilJs components are available in the Angular project, but they render without any style whatsover and the slot behavior doesn't work at all.

**Expected behavior:**
Any component from stenciljs renders as expected with it's correct styles

**Other information:**
Currently the StencilJs library is not published in npm, so I'm using `npm link` to consume it in Angular. 
I also tried with a React project with CRA, consuming directly the dist/ folder and it works as a charm.

Finally, I did all the steps in the documentation regarding Angular projects. Added `CUSTOM_ELEMENTS_SCHEMA` to app.module.ts and defineCustomElements(window); in main.ts.

I'm not sure how to continue debugging it, the styles are present in the node_modules/<my_package>/dist folder, but just not being rendered.

**Comment by rwaskiewicz** [comment]
Hey there 👋 

I apologize it took so long for someone on the team to acknowledge this issue. At this time, Stencil v1 and lower is no longer supported.  As a result, I'm going to close this issue.

If this issue is still occurring in Stencil v2, can you please create a new issue for us with a minimal reproduction case? Thanks!
