### ISSUE TITLE
E2EPage  - `page.goTo` is not a function

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/stencil#2538]
**Stencil version:**
```
 @stencil/core@1.15.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

```
const page = await newE2EPage({ url: '/' });
await page.goTo('/foo');
```

Run: `npm test -- --e2e`
=> `TypeError: page.goTo is not a function`

**Expected behavior:**

It works.

---

Same thing as #1237, not sure how long this has not been working.

**Comment by Mykola-Veryha** [comment]
I got the same error

**Comment by rwaskiewicz** [comment]
👋 

I apologize that it took so long for a member of the team to respond to this issue. This is still an issue in Stencil v3. I'm going to label this to get it ingested into our backlog.

**Comment by christian-bromann** [comment]
Hi [Issue Author] 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
