### ISSUE TITLE
Cannot test behavior after select change event

### ISSUE THREAD

**Issue by markcellus** [ionic-team/stencil#2580]
**Stencil version:**

```
 @stencil/core@1.15.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm unable to test behavior after a `change` event is emitted from a `<select>` element. 

**Expected behavior:**
I'm able to test behavior after a `change` event is emitted from a `<select>` element. 

**Steps to reproduce:**

```tsx
// select-cmp.tsx
import { h, Component, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'select-cmp',
  shadow: true,
})
export class SelectCmp {
  @Event() selected: EventEmitter<string>;

  private changed(e: Event) {
    const select = e.target as HTMLSelectElement;
    const { selectedIndex, options } = select;
    const selectedOption = options[selectedIndex];
    this.selected.emit(selectedOption.value);
  }
  render() {
    return (
      <select onChange={(e) => this.changed(e)}>
        <option value="first">One</option>
        <option value="second">Two</option>
      </select>
    );
  }
}
```

```ts
// select-cmp.spec.ts
import { newSpecPage } from '@stencil/core/testing';
import { SelectCmp } from './select-cmp';

describe('Select Cmp', () => {
  it('emits an event with the theme selected', async () => {
    const testThemeValue = 'first';
    const page = await newSpecPage({
      components: [SelectCmp],
      html: '<select-cmp></select-cmp>',
    });
    const selectedListenerSpy = jest.fn();
    const component = page.root as any;
    component.addEventListener('selected', selectedListenerSpy);
    const select = component.shadowRoot?.querySelector('select') as HTMLSelectElement;
    select.value = testThemeValue;
    const event = new CustomEvent('change', { composed: true, bubbles: true });
    select.dispatchEvent(event);
    expect(selectedListenerSpy).nthCalledWith(1, testThemeValue);
  });
});

```

**Comment by tanner-reits** [comment]
Hi @markcellus  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
