### ISSUE TITLE
"componentWillLoad", "componentWillRender" and "routerDirection" behave inconsistently

### ISSUE THREAD

**Issue by Fernito69** [ionic-team/stencil#2645]
**Stencil version:**

```
@stencil/core@1.17.3 
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
The behavior of componentWillLoad() and componentWillRender() is quite inconsistent, as they don't get triggered every time when a page is loaded. The transitions between pages are also behaving inconsistently. Even though "routerDirection" is set to "forward" in every case, some times the transition goes forward and some times backwards.

**Expected behavior:**
I might be wrong, but I suppose componentWillLoad() and componentWillRender() should get executed every time the page is accessed.

**Steps to reproduce:**
Here I provide a video showing the issue. I have a componentWillLoad and a componentWillRender with a console.log on them in every page. Some times they get triggered, and some times they don't. For me the weirdest thing about it is that when I go from "dashboard" to "project" and back through the first list item, it has a completely different behavior as when I do it through the second list item.

[https://www.youtube.com/watch?v=xCJcp6NByVo](https://www.youtube.com/watch?v=xCJcp6NByVo)

**Related code:**

Here's a link to the [repo](https://github.com/Fernito69/todo-v2/tree/issue/src/components). The involved components are basically "app-dashboard" and "app-project". Sorry if the code is a little bit sloppy, but I've been doing a lot of tests with it. I'm also quite new to programming, so probably some of my practices are not ideal.

Thank you in advance.

**Comment by tanner-reits** [comment]
Hi @Fernito69  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
