### ISSUE TITLE
Tests fail when using JSDOM test environment

### ISSUE THREAD

**Issue by danschultz** [ionic-team/stencil#2653]
**Stencil version:**

```
 @stencil/core@1.17.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When setting Jest's test environment to JSDOM, tests will fail with:

```
 FAIL  src/utils/utils.spec.ts
  ● format › returns empty string for no names defined

    TypeError: Cannot read property '_location' of null

      at Window.get location [as location] (node_modules/jsdom/lib/jsdom/browser/Window.js:256:79)
      at Proxy.resetPlatform (node_modules/@stencil/core/internal/testing/index.js:1015:35)
      at Object.beforeEach (node_modules/@stencil/core/testing/index.js:3572:11)
```

**Expected behavior:**

Tests shouldn't throw an exception

**Steps to reproduce:**

1. Initialize a new stencil project via `npm init stencil`.
2. Update your `stencil.config.js` to include:  
```js
export const config: Config = {
  testing: {
    testEnvironment: 'jsdom',
  },
};
```
3. Run `yarn test`

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by chiyema** [comment]
Just encountered the same issue. Trying to override `testEnviroment` to `jsdom` because codes are accessing `Document`. According to the [article](https://medium.com/@tally_b/unit-testing-stenciljs-1-0-c4e902a4e63c), Stencil doesn't support `jsdom` on purpose because `jsdom` doesn't support web component api.

Besides, I found a jsdom alternative [happy-dom](https://www.npmjs.com/package/@happy-dom/jest-environment) that supports web components but still no luck when running the unit testing.
