### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rufatZZ** [ionic-team/stencil#2655]
I'm getting this error after every `npm test` command. I can't a single successful test from beginning. I was getting same error in `v: 1.12.2`, then i updated to latest version, nothing changed. Couldn't find related solution. 

**Stencil version:**

```
 @stencil/core@<1.17.3>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

```
C:\**\**.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { newSpecPage } from '@stencil/core/testing';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)

```
**Related code:**

```tsx
import { KbBadge } from './kb-badge';
import { newSpecPage } from '@stencil/core/testing';

describe('kb-badge', () => {
  it('renders', async () => {
    const page = await newSpecPage({
      components: [KbBadge],
      html: `<kb-badge></kb-badge>`,
    });
    expect(page.root).toEqualHtml(`
      <kb-badge>
        <mock:shadow-root>
          <slot></slot>
        </mock:shadow-root>
      </kb-badge>
    `);
  });
});
```

**Other information:**

package.json
```
  "devDependencies": {
    "@stencil/core": "1.17.3",
    "@stencil/sass": "^1.3.1",
    "@types/jest": "24.9.1",
    "@types/puppeteer": "2.0.1",
    "jest": "24.9.0",
    "jest-cli": "^24.9.0",
    "puppeteer": "2.1.1"
  }
```

**Comment by rwaskiewicz** [comment]
Hey there!

I apologize that it took so long for a member of the Stencil team to respond to this issue. I understand something like this can be frustrating - I've taken a look at the provided code and was unable to reproduce this issue. I think the root cause can be related to one (or more) things:
- there's something in `KbBadge` that is causing the issue, which I don't have access to at the moment
- this was a bug in Stencil that was resolved at some point

In either case, if you're willing/able to provide an updated reproduction case for the team to take a look at, I'd greatly appreciate it! If not, I completely understand. Thank you for taking the time to put together this issue and to help make Stencil better, and I apologize again for the lack of response.
