### ISSUE TITLE
@ sign in CSS selector not parsed correctly

### ISSUE THREAD

**Issue by gregorypratt** [ionic-team/stencil#267]
**Stencil version:**

```
 @stencil/core@0.0.6 
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When I write some SCSS like this:
```scss
.container--small {
  ...
}
```
Everything is fine.

But if I use an `@` in the selector it doesn't seem to work correctly...
```scss
.container--small\@tablet {
  ...
}
```

**Expected behavior:**
I would expect the CSS to be outputted correctly

**Comment by jgw96** [comment]
Hey! Is there a specific use case for why you have a `\` and an `@` in your selector? Im not sure that is actually a valid css selector

**Comment by gregorypratt** [comment]
That’s in my scss. 

The outputted CSS should be `.container—small@tablet

**Comment by brandyscarney** [comment]
Note to team:

I confirmed that `.container—small\@tablet` is valid CSS, and Sass should be keeping the `\` when it compiles to CSS. Adding the following to the fab, for example:

```
.fab\@tablet {
  color: red;
}
```

Is showing up in `ion-fab.ios.js` correctly as:

```
Ionic.loadStyles("ion-fab-button_ios",".fab\@tablet {\n  color: red;\n}\n\n
```

but the actual CSS being loaded is wrong:

```
.fab@tablet {
  color: red;
}
```

Which results in this being ignored because it doesn't have the `\`. 

Example codepen: https://codepen.io/brandyshea/pen/ooXMpW

**Comment by adamdbradley** [comment]
Awesome thanks @gregorypratt and @brandyscarney for reporting and debugging this, should be fixed in the next release, thanks!
