### ISSUE TITLE
Creating customer elements in test, connectedCallback does not appear to ever be called

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2676]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The following tests rely on some customer elements that create SD content in their connectedCallback() callback methods. However, when these tests are run using Stencil's test harness the connectedCallback() appears to not be run at all.

https://github.com/Esri/calcite-components/pull/982/files 

The current repo uses an old version of jest that has an old version of jsdom, but the problem also occurs if I update to the latest jest thus updating the jsdom version past this: https://github.com/jsdom/jsdom/blob/master/Changelog.md#1620

**Expected behavior:**
The user's test appears valid, so I am expecting it to work, but as noted above the connectedCallback() is never called, so the DOM is never updated as expected.
'
**Steps to reproduce:**

1. clone repo linked above.
1. checkout the jcfranco/allow-getting-closest-across-shadow-boundary branch
1. run the tests

**Comment by christian-bromann** [comment]
Hi @kensodemann  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
