### ISSUE TITLE
E2E test: keep browser window open

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#2693]
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] feature request

**Current behavior:**
Setting `browserHeadless: false` in `stencil.config.ts`, makes the browser window visible during tests. However, it closes as soon as the test is finished.

**Expected behavior:**
Provide an option to make the browser window stay open afterwards, e.g. to inspect the DOM.

**Comment by christian-bromann** [comment]
Hi @kraftwer1 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we are now supporting more frameworks to test Stencil components, e.g. [WebdriverIO](https://stenciljs.com/docs/testing/webdriverio/overview) or [Playwright](https://stenciljs.com/docs/testing/playwright/overview). We believe that these tools are much better suited for testing Stencil components and don't plan improving the built-in testing experience much further, except for bug fixes.

Please let me know if you have any questions!

Thank you for your understanding and support of StencilJS!
