### ISSUE TITLE
Document complex types

### ISSUE THREAD

**Issue by SheepFromHeaven** [ionic-team/stencil#2747]
**Stencil version:**
```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Complex typed props are printed just as the interface name in the readme docs.

**Expected behavior:**
A prop typed with an interface is printing the whole interface in the docs. Preferably as an own code block unter the props docs.

**Steps to reproduce:**
- create a component
- add a prop
- type the prop with an interface

**Comment by SheepFromHeaven** [comment]
I tried looking into the issue and got stuck inside the `parseStaticProps` / `getStaticValue` functions. I tried passing through the ts.TypeChecker to them and using `typeChecker.typeToString(typeChecker.getTypeAtLocation(<propNode>))`.
This sadly only returned `any`.
So if you have any hints to where I can look into, I am happy to help.

**Comment by alicewriteswrongs** [comment]
@SheepFromHeaven thanks for filing this issue and I apologize it took so long for anyone from the Stencil team to get back to you!

The question of the best way to render type information in our autogenerated `README.md` files is a bit of a complicated one. For small interfaces, for instance (something like `{ name: string }`), presenting the structure of the interface rather than it's name might allow a component user to get up to speed more quickly, without having to go look up what concrete type a given interface corresponds to. On the other hand, well-known names might communicate more directly what a component expects, for instance a `MutationObserver` instance or an `HTMLInputElement`.

In any case, exactly how best to do this is something of an evolving conversation. Right now, I'm going to close this in favor of a newer issue (#3603) which deals with the same problem — I'd invite you to contribute to the conversation over there!

Thanks again for filing, and many apologies for the lack of response.
