### ISSUE TITLE
[feat] add stencil to the iconic js-framework-benchmark by Stefan Krause

### ISSUE THREAD

**Issue by trusktr** [ionic-team/stencil#2765]
Here are the current results (Stencil isn't there): https://krausest.github.io/js-framework-benchmark/current.html

It would be great to add Stencil. Here's the repo: https://github.com/krausest/js-framework-benchmark

**Comment by LifeIsStrange** [comment]
@adamdbradley friendly ping, having stencil added to this de facto standard benchmarck would help my company gain confidence in using stencil, otherwise the performance is an unknown. Being the fastest is not a requirement, just being not *too* far from the 4 mainstream Vdoms :) plus given the compilation nature of stencil it might have great performance potential like svelte. Such a benchmarck could help stencil get more recognition / widely used.
Also, the core stencil devs are probably the best fit for doing the best implementation.

**Comment by ryansolid** [comment]
Ok I caved and made something. Could benefit from review. The challenge is structually the table doesn't allow for custom elements, and as far as I can tell Stencil doesn't support native built-ins. Often this doesn't matter as many implementations use a single component, but given Stencil uses a VDOM my hunch is while this maximizes creation it hurts updates on nested values. Without another way to split out child updates this is the best I can do. But I could also just be less familiar with Stencil.

https://github.com/krausest/js-framework-benchmark/pull/879

**Comment by alicewriteswrongs** [comment]
Hey all, apologies that this issue sat for a while with no response from the Stencil team!

Huge props to @ryansolid for adding Stencil to the benchmark, we really appreciate it :)

As part of an effort to clean out old issues I'm going to close this now, @trusktr (or anyone else!) feel free to open a new issue if there's more you'd like to see on this front.
