### ISSUE TITLE
In some cases, Using dash-case attributes does not work in JSX!

### ISSUE THREAD

**Issue by Aswathprabhu** [ionic-team/stencil#2772]
**Stencil version:**

```
 @stencil/core@1.17.4
```

**I'm submitting a:**

- [X] bug report

**Current behavior:**
If you define a `camelCase` Boolean property in the component and default that to true, then try to set it to false via the attribute on the custom element using `dash-case` , It doesn't update. If the component Prop is false by default, things work normally. Just a bit confused with this behavior.

**Expected behavior:**
It should just work normally. `dash-case` attributes works mostly and only in this particular case things just don't work.

**Steps to reproduce:**
```tsx
@Prop() showButton: boolean = true;
<my-custom-element show-button={false}>  - does not work in JSX (yet dash-case works in every other scenarios) 
```

**Comment by AlexSapoznikov** [comment]
@Aswathprabhu Probably `false` is passed as string and it is a truthy value.
You could try something like this:

```
const comp = document.querySelector( 'my-component' )
comp.showButton = false;
```

**Comment by Aswathprabhu** [comment]
@AlexSapoznikov, The following works seamlessly in plain HTML

```tsx
<my-custom-element show-button="false">
```

Only in `jsx` I'm facing the issue.

**Comment by mkay581** [comment]
@AlexSapoznikov AFAIK, this is expected behavior when using JSX for HTML boolean attributes. When you do this in JSX:

```html
<my-custom-element show-button={false}>
```

It gets compiled to this HTML:

```html
<my-custom-element>
```
And when you do this in JSX:

```html
<my-custom-element show-button={true}>
```
It gets compiled down to this HTML:

```html
<my-custom-element show-button>
```

So that's why you're seeing different behavior. It's how JSX works. The closest explanation I can find of this behavior is in [React's JSX in Depth](https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored) documentation.

To get what you're looking for, I believe you can convert the `false` to a string first:

```html
<my-custom-element show-button={String(false)}>
```

**Comment by claviska** [comment]
Yes, this is expected. Always use the camelcase variation in JSX. 😄 

```jsx
<my-custom-element showButton={false}>
```

**Comment by Aswathprabhu** [comment]
@claviska Also facing this issue in handlebars (Ember js templates). Are we supposed to use camelCase there too?

**Comment by claviska** [comment]
> Also facing this issue in handlebars (Ember js templates). Are we supposed to use camelCase there too?

I'm not familiar with Ember, but it probably doesn't know to map camelcase props to kebab-case, so it should probably be the latter.
