### ISSUE TITLE
onClick doesn't fire by Space or Enter key on a custom button element is focused

### ISSUE THREAD

**Issue by RezaRahmati** [ionic-team/stencil#2783]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
onClick doesn't fire

**Expected behavior:**
onClick happens

**Steps to reproduce:**

**Related code:**
Steps to reproduce:
1- create a custom button component like below
```tsx

@Component({
    tag: "idv-button",
    styleUrl: "idv-button.scss",
    shadow: true,
})
export class IdvButton {

    render(): any {
        return (
            <Host tabindex="0" role="button" >
                <button >
                    <slot></slot>
                </button>
            </Host>
        );
    }
}

```
2- add it to another component like this
```tsx
    startClick(): void {
       console.log(click);
    }
                        <idv-button
                            onClick={this.startClick.bind(this)}>
                             My Button
                        </idv-button>
```
3- Now use tab button to navigate to this button
4- when it's focused, use Enter or Space

Expected:
onClick happens

Actual:
Nothing happens

**Other information:**

**Comment by claviska** [comment]
The problem is that you've added `tabindex` to the host element, specifically `<idv-button>`. Because of that, this is the element that receives focus when you hit tab, not the button. You'll notice a subsequent tab press will move focus to the internal `<button>` element, at which point you _will_ receive events as expected.

This isn't a great idea since users will have to tab through buttons twice. Removing `tabindex` from your host element will allow the button to act in a way that both you and your users expect and, since events in the shadow DOM are retargeted to the host element, you can continue listening to them on the host element.

Hope that helps!
