### ISSUE TITLE
Live reload does not reload automatically on file save. (sometimes)

### ISSUE THREAD

**Issue by y0nd0** [ionic-team/stencil#2817]
**Stencil version:**

```
 @stencil/core@2.0.1
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**

The live reload does not reload automatically on file save. I have to click on the page reload button of the browser. 

**Expected behavior:**
`expectedBehavior = !currentBehavior` Live reload should always work.

**Steps to reproduce:**
Just create a new project, remove the default component. Create a new one. 
The live reload sometimes not work. It's a gambling.

**Related code:**

```tsx
stencil build --dev --watch --serve
```

**Other information:**
 I don't know what the problem is. It'S a brand new project. No changes. Just created my component. I use the scss plugin. Not yet tested, without it.

It can be difficult to reproduce. But I was wondering if you - Ionic Team - are working with this you should have the same problems. Sometimes. I'm pretty sure you have the same problems. It's nothing to reproduce in a minute. You have to work with it. Creating a real world project. ...

I'm on Windows 10, Chrome, ...
Let me know if you need more infos. And if there are some configs or hacks I could do, to fix that.

**Comment by rwaskiewicz** [comment]
Sorry folks, this shouldn't have been closed. I've put up a [PR](https://github.com/ionic-team/stencil/pull/3267/files) to fill this missing case in our repo bot. Thanks for your patience!

**Comment by christian-bromann** [comment]
Hi @y0nd0  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
