### ISSUE TITLE
Property 'autoComplete' does not exist on type 'TextareaHTMLAttributes<HTMLTextAreaElement>'

### ISSUE THREAD

**Issue by joao-m-santos** [ionic-team/stencil#2882]
**Stencil version:**

```
 @stencil/core@2.5.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Setting the `autoComplete` or `autocomplete` attributes of a `<textarea>` causes the error:
```Property 'autoComplete' does not exist on type 'TextareaHTMLAttributes<HTMLTextAreaElement>'```

**Expected behavior:**
There should be no error popping up.

**Related code:**

```tsx
<textarea autoComplete="on"></textarea>
```

**Other information:**
Typescript version: 3.9.9

**Comment by rwaskiewicz** [comment]
The fix for this issue has been [officially released as a part of Stencil 3.4.0](https://github.com/ionic-team/stencil/releases/tag/v3.4.0). Folks running into this issue should update to v3.4.0 at minimum. I'm going to close this out following the release, but please feel free to open a new issue should this reappear. Thanks!
