### ISSUE TITLE
The no-module script from dist output is not minified

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2911]
If you do a production build or a build with the `minifyJs` Stencil config option enabled, the no-module script does not get minified entirely. You can see this in the following:

No-module script is not minified
https://unpkg.com/browse/@esri/calcite-components@1.0.0-beta.55/dist/calcite/calcite.js

ESM is minified as expected
https://unpkg.com/browse/@esri/calcite-components@1.0.0-beta.55/dist/calcite/calcite.esm.js

**Comment by christian-bromann** [comment]
Hi @kensodemann 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
