### ISSUE TITLE
Dev process in watch mode does not pick up new files

### ISSUE THREAD

**Issue by patrickhaug** [ionic-team/stencil#2953]
**Stencil version:**
```
 @stencil/core@2.6.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
A running dev process does not pick up newly added files. Only restart fixes this problem.
**Expected behavior:**
When dev is running and a new file (component) is added, transpile process and rollup should  pick it up.
**Steps to reproduce:**
Have a running dev instance and add a new file to the components.

**Comment by zemlakov** [comment]
I got the same problem. I've tried with older version of stencil and it reproduce as well. When I copy paste any of existing components and then rename it and correct selector name to unique  - stencil still show issue - 'Use unique indentifier'.
As far as I understand problem is because it doesn't update components.d.ts. After restart it successfully compiles.

**Comment by splitinfinities** [comment]
Heads up that this should be solved with https://github.com/ionic-team/stencil/pull/3001 and will be a part of the next version.

**Comment by splitinfinities** [comment]
Solved in v2.7.0! 🎉

**Comment by patrickhaug** [comment]
This is actually not fixed in the referenced version.
