### ISSUE TITLE
feat: Opt in for polyfilling when creating dist-custom-elements-bundle

### ISSUE THREAD

**Issue by Arvind6353** [ionic-team/stencil#3070]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/master/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/master/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi Team,

Do we have an option to opt in for **polyfills** when creating **dist-custom-elements-bundle**.

When we use **dist(lazyload)** build , polyfills gets baked in.

In the docs , its mentioned that for **dist-custom-elements-bundle**, the consumer has to provide polyfills if they support older browsers.

Is it possible to include an option to manually opt in for polyfills along with **dist-custom-elements-bundle** ?

### Describe the Use Case

We wanted to use dist-custom-elements-bundle with react that comes with tree shaking capability.

But we want to support **IE11 browser** and it would be great, if you can allow to opt in for polyfilling when creating **dist-custom-elements-bundle**

When we use lazy load dist bundle in IE11, its working well. Kindly consider this usecase of providing polyfills for the other bundles. 

Thanks

**Comment by rwaskiewicz** [comment]
Hey folks 👋 

I'm going to close this feature request out. Unfortunately, it hasn't received as many updates as we'd like to see since it's original opening. While we'd like to accept every feature request, we are unfortunately unable to do so. We'd be willing to revisit this some time in the future if someone was able to add on to the case for it/if it receives more 👍's. Thanks!
