### ISSUE TITLE
feat: Proxy Dev Server

### ISSUE THREAD

**Issue by jjmato** [ionic-team/stencil#3102]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Request for that development server supports proxying files from another server for given URL

### Describe the Use Case

I need config porxy 

### Describe Preferred Solution

So it can be configured like this in stencil.config.js:
```
exports.devServer = {
  root: 'www',
  watchGlob: '**/**',
  proxy: {
    '{URL_PATTERN}': '{API_URL}'
  }
}
```

**Comment by klh** [comment]
personally i think you should remove the devServer entirely and show an example of how to do it via koa or express - its not a lot of lines of code to get that working, and by exposing all the internals (for instance via a koa server example) people can add whatever they want to it - here for instance a proxy middleware.

alternatively you could easily use a koa-middleware to do everything you need to get done and just use that.

saves on your dev time and resources as well

**Comment by rwaskiewicz** [comment]
Hey folks 👋 

I'm going to close this feature request out. Unfortunately, it hasn't received as many updates as we'd like to see since it's original opening. While we'd like to accept every feature request, we are unfortunately unable to do so. We'd be willing to revisit this some time in the future if someone was able to add on to the case for it/if it receives more 👍's. Thanks!
