### ISSUE TITLE
feat: Allow to pass custom options to Puppeteer screenshot function

### ISSUE THREAD

**Issue by ryuran** [ionic-team/stencil#3145]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

We expect to be able to pass any options possible to puppeteer screenshot option.

Currently we have only ScreenshotOptions interface.
https://github.com/ionic-team/stencil/blob/main/src/testing/puppeteer/puppeteer-screenshot.ts#L138-L156
```typescript
function createPuppeteerScreenshopOptions(opts: ScreenshotOptions) {
  const puppeteerOpts: puppeteer.ScreenshotOptions = {
    type: 'png',
    fullPage: opts.fullPage,
    omitBackground: opts.omitBackground,
    encoding: 'binary',
  };

  if (opts.clip) {
    puppeteerOpts.clip = {
      x: opts.clip.x,
      y: opts.clip.y,
      width: opts.clip.width,
      height: opts.clip.height,
    };
  }

  return puppeteerOpts;
}
```

### Describe the Use Case

We spot this issue : https://github.com/puppeteer/puppeteer/issues/7251

A resize event happen just before screenshot so it trigger some resize event listener able to redraw the component we try to screenshot.

This resize is unwanted but, with the current stencil testing API, we are not able to avoid it by the solution proposed in the issue: pass the option `captureBeyondViewport: false`

**Comment by Perronef5** [comment]
We need this fix urgently 🙏🙏

**Comment by ryuran** [comment]
We use this monkey patch to temporary workaround this issue waiting for an internal fix into stencil:
https://github.com/ionic-team/stencil/issues/3188

**Comment by christian-bromann** [comment]
Hi @ryuran  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we are now supporting more frameworks to test Stencil components, e.g. [WebdriverIO](https://stenciljs.com/docs/testing/webdriverio/overview) or [Playwright](https://stenciljs.com/docs/testing/playwright/overview). For visual screenshot testing we recommend to use their visual capabilities as we are about to deprecate Stencils screenshot feature.

Please let me know if you have any questions!

Thank you for your understanding and support of StencilJS!
