### ISSUE TITLE
bug: getAssetPath is not defined when using dist-custom-elements

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/stencil#3208]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.12.0

### Current Behavior

In our use case, we have a component that relies on `getAssetPath` to build a `URL` object. When using a lazy loaded component bundle, `getAssetPath` is automatically set by Stencil. When using dist-custom-elements, this path is not set for us.

As a result, when we try to construct the URL we get the following:

```
index.js:2680 Uncaught TypeError: Failed to construct 'URL': Invalid base URL
    at getAssetPath (index.js:2680)
    at getNamedUrl (utils.js:47)
    at getUrl (utils.js:28)
    at HTMLElement.loadIcon (ion-icon.js:146)
    at ion-icon.js:118
    at HTMLElement.waitUntilVisible (ion-icon.js:141)
    at HTMLElement.connectedCallback (ion-icon.js:116)
    at HTMLElement.connectedCallback (index.js:2280)
    at Object.parcelRequire.src/index.js.ionicons/components/ion-icon.js (index.js:15)
    at newRequire (src.a2b27638.js:47)
```

According to https://github.com/ionic-team/stencil/commit/a06a9419b23f0f2624226162744d63bd6a8cfcce#diff-3e7791ed47b552cf32b27be24a50b9e8592177d6e2f1c82d1d9399976ab2e9acR277, this seems to be an intentional behavior, but the alternatives listed in the comment do not work for us because we need this component to run in multiple environments.

For example, using `import.meta.url` does not work in Jest because it does not support ES Modules. Using `process.env.ASSET_PATH` does not work in the browser because `process` is not defined.

### Expected Behavior

I would expect there to be a reliable way to set `getAssetPath` or have `getAssetPath` automatically set when using dist-custom-elements.

### Steps to Reproduce

1. Clone repo. Make sure you are on the `ionicons` branch.
2. Run `npm install`.
3. Run `npm run start`.
4. Open the dev tools. Observe that the `Invalid base URL` error is present.
5. In `index.js` uncomment lines 5-10.
6. Save the file and open dev tools.
7. When the page reloads, observe that the error is gone because we are providing the SVG data directly.

### Code Reproduction URL

https://github.com/liamdebeasi/core-vanilla-ce/tree/ionicons

**Comment by MarianDabrowski** [comment]
@liamdebeasi is there any update on this issue?

**Comment by rwaskiewicz** [comment]
After diving into this issue further, we have determined that `getAssetPath` and `setAssetPath` are working as intended here.  Stencil cannot set the asset path for users by default for the `dist-custom-elements` output target, as it’s difficult for Stencil to know the architecture of the application(s) that will be using this API. For example, the same component library (containing components that make use of assets) can be used in separate projects, each with their own, distinct directory structures.  Furthermore, that component library may be used differently across projects - in one case it may be consumed directly in a web application, while it may simultaneously be consumed by a separate web component library.

We do acknowledge this is a difficult API to work with at the moment, primarily due to lack of ESM support in Jest, which makes passing a value of `import.meta.url` to `setAssetPath` close to impossible.  We’re going to continue to monitor Jest for signal of ESM support and are looking to see if bringing Jest 27's experimental ESM support to Stencil will help alleviate this particular issue

As a result of this issue report, we’ve re-written our assets documentation to better explain this API:
https://stenciljs.com/docs/assets#assets

**Comment by dasa** [comment]
What's the recommended way to see if the assets path has been set or not? Is it to try/catch `getAssetsPath`?
