### ISSUE TITLE
localStorage with prerendering

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil#332]
I am using localStorage to keep my application state so it persist, I would be great that stencil offline rendering could implement some non-persistent API for it ?

<img width="531" alt="screen shot 2017-11-25 at 17 27 59" src="https://user-images.githubusercontent.com/127379/33232407-2a200eae-d206-11e7-880f-8ccde00ef973.png">

**Comment by jgw96** [comment]
Any reason you couldnt just use `!isServer` to stop this error? Thats what ive done in multiple apps.

**Comment by manucorporat** [comment]
sure! that's in fact what I did. I opened this to discuss if it makes sense to provide "localStorage" during server rendering

**Comment by bfmatei** [comment]
This is a longer discussion. Usually you don't need localStorage during pre-rendering, mainly because it defeats the purpose of localStorage. Every pre-render is a one time only process. Using localStorage as session-based storage is an anti-pattern from my point of view and it should be avoided (I saw an app which was keeping the user data in local storage and it was hard to debug, hard to maintain etc.)

**Comment by jgw96** [comment]
Hey all! I am going to close this issue for now as the official recommendation is to use the `isServer` utility in this case. At this time we do not believe that localStorage should be used during pre-rendering. Thanks for using Stencil!
