### ISSUE TITLE
bug: can't get experimentalImportInjection to work with vite

### ISSUE THREAD

**Issue by janniks** [ionic-team/stencil#3407]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.16.1

### Current Behavior

 Dynamic import failure on vite/rollup still persists.

### Expected Behavior

Rebuilding with latest `experimentalImportInjection` should solve dynamic import failure on vite/rollup.

### Steps to Reproduce

- Visit this codesandbox: https://codesandbox.io/s/priceless-mcclintock-2x9n30

OR

- `git clone git@github.com:hirosystems/create-stacks.git`
- `cd templates/template-vue`
- `npm install @stacks/connect@5.0.6-alpha.6be82fd.0 @stacks/connect-ui@5.0.6-alpha.6be82fd.0`
- `npm start`

---

- click `Connect Wallet` button
- → dynamic import fails, as previously

## Background

We have a fairly stock vue+vite sample projects in: https://github.com/hirosystems/create-stacks/tree/main/templates/template-vue → used for codesandbox

The stencil component was [updated](https://github.com/hirosystems/connect/pull/238/files) to `experimentalImportInjection` under 2.16.1. The component was [rebuilt and released](https://github.com/hirosystems/connect/runs/6729570652?check_suite_focus=true) via npm as `@stacks/connect-ui@5.0.6-alpha.6be82fd.0`.

---

CC @rwaskiewicz https://github.com/ionic-team/stencil/issues/2827#issuecomment-1142399806

### Code Reproduction URL

https://codesandbox.io/s/priceless-mcclintock-2x9n30

### Additional Information

Is it possible to fix this issue with the [@rollup/plugin-dynamic-import-vars](https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars) plugin? If so how?

I've tried similar things to the following:

```js
dynamicImportVars({
  include: "./node_modules/@stacks/connect-ui/dist/connect-ui/*",
}),
```
Where `connect-ui` is a stencil component via plain `dist`, but used via another dependency (`connect`).

**Comment by janniks** [comment]
@rwaskiewicz do you think there's an easy way to fix this? Otherwise it might make more sense to use `dist-custom-elements` and manually chunk in the vite config itself. 🤔

**Comment by rwaskiewicz** [comment]
@janniks 

I took a look at the reproduction case and can confirm that the dynamic import is failing.  Looking at `create-stacks/templates/template-vue/node_modules/.vite/deps/@stacks_connect.js`, it looks like Vite is currently caching a version of `@stacks/connect` that is not dynamically importing components. I'm able to discern this based on the following line in the file:
```
/*!__STENCIL_STATIC_IMPORT_SWITCH__*/
```
which should be replaced with the import statements for your components.  I _believe_ this is part of the root cause - although I'm not sure how `@stacks/connect` is generated/built, which makes it a little tricky to proceed here.  Off the top of my head, I can see a few possibilities:
1. The configuration for dynamically importing components isn't set for `@stacks/connect` in `stencil.config.ts`
2. The configuration for dynamically importing components isn't being set correctly internally within Stencil
3. Vite is caching an older version of Stencil, which is causing the dynamic imports to not be generated correctly.

Can you do me a favor and validate that [experimentalimportinjection](https://stenciljs.com/docs/config-extras#experimentalimportinjection) is set on `@stacks/connect`? Can you provide a reproduction case/branch that points me to how it's configured after that? I have a sneaky suspicion that it's the third option there, but wanna rule out the first two options first.

**Comment by janniks** [comment]
The `@stacks/connect` dependency itself loads the stencil component [like this](https://github.com/hirosystems/connect/blob/0061735486a04ed2de73ccf57c10350526dd8cad/packages/connect/src/ui.ts#L13) from the actual stencil component dependency `@stacks/connect-ui`. Does that make a difference / Could that be a problem? 😬

**Comment by rwaskiewicz** [comment]
> The @stacks/connect dependency itself loads the stencil component [like this](https://github.com/hirosystems/connect/blob/0061735486a04ed2de73ccf57c10350526dd8cad/packages/connect/src/ui.ts#L12-L13) from the actual stencil component dependency @stacks/connect-ui. Does that make a difference / Could that be a problem? 😬

Potentially, it depends what that `defineCustomElements` function you link to is defined/what it's doing.  It's not immediately clear to me if that's a Stencil generated loader package or something else 🤔

**Comment by janniks** [comment]
Yes, that's all stencil generated. Same method as used [here in stencil docs](https://stenciljs.com/docs/vue#vue-plugin), and [here](https://sourcegraph.com/search?q=context:global+defineCustomElements+and+loader&patternType=literal).

Is there a better method of loading for use in another library?

**Comment by janniks** [comment]
I updated to stencil core 2.17 ([here](https://github.com/hirosystems/connect/pull/238)) but it still doesn't work. The way we import is the same as [most stencil examples / ionic use-cases](https://sourcegraph.com/search?q=context:global+defineCustomElements+and+loader&patternType=literal).
The `loader` is set up in the same way ionic core is.

- `esmLoaderPath: '../loader'` in dist target (I have also tried leaving loader in the dist folder, same result)
- use `defineCustomElements` from loader

Still doesn't work 😣
