### ISSUE TITLE
bug: rollup build cannot tree-shake properly when using dist-custom-elements + defineCustomElement + setAssetPath

### ISSUE THREAD

**Issue by jcfranco** [ionic-team/stencil#3470]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.17.1

### Current Behavior

A rollup build of an app that uses `setAssetPath` and imports a subset of components (built w/ Stencil 2.17.1 + `defineCustomElement: true`), will not tree-shake properly and include code for **all** components. 

### Expected Behavior

The main bundle should only have code relevant to the imported component.

### Steps to Reproduce

See README from [repro case repo](https://github.com/jcfranco/stencil-use-case-where-build-is-not-tree-shaken/blob/master/README.md).

### Code Reproduction URL

https://github.com/jcfranco/stencil-use-case-where-build-is-not-tree-shaken

### Additional Information

This started after the single file export of all components got introduced by [Stencil v2.17.0](https://github.com/ionic-team/stencil/blob/main/CHANGELOG.md#-2170-2022-06-21).

A couple of suggestions to address this:

1. Add an option to `dist-custom-elements` to enable/disable exporting all components from `index.js`
2. Provide another way of importing `setAssetPath`

**Comment by alicewriteswrongs** [comment]
Hi @jcfranco, thanks for filing this issue! I'm going to mark this for further discussion and refinement so we can figure out what to do exactly.

**Comment by christian-bromann** [comment]
Hi @jcfranco 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!
