### ISSUE TITLE
Type is not imported correctly in components.d.ts.

### ISSUE THREAD

**Issue by insiders-technologies** [ionic-team/stencil#3975]
**Stencil version:**
2.21.0

**Current behavior:**
Certain types are not correctly imported in the components.d.ts, while the error does not occur for other types.
  
The type 'TextboxSetting' is declared in my-component.tsx and imported in my-toggle.tsx.
However, it is imported as 'TextboxSetting' and is used as 'TextboxSetting1'  in the automatically-generated interface.
![image](https://user-images.githubusercontent.com/122532382/212067664-46851844-a7ec-407b-b564-6953f3d031d5.png)

The build therefore fails with the error " 'TextboxSetting1' not found."
![image](https://user-images.githubusercontent.com/122532382/212067372-516d12c9-f298-4d25-8443-f687e2ffa640.png)

**Expected behavior:**
The type is imported with its correct name 'TextboxSetting' in the automatically-generated interface.

**GitHub Reproduction Link:**
https://github.com/insiders-technologies/stencil-minimal-component

**Other information:**
The error does not occur with certain variations of the name, such as '**_TextboxSettings_**'.

**Comment by alicewriteswrongs** [comment]
Hi @insiders-technologies, thanks for reporting this issue!

I checked out your reproduction case (thank you for providing that btw!) but I wasn't able to reproduce the error you're reporting.

I cloned your repo and then ran `npm run build`, and I'm seeing the build finish successfully. It looks like perhaps the reproduction is drawn from a larger project, is it possible there's another element necessary to reproduce the issue?

**Comment by jnessel** [comment]
Hi @alicewriteswrongs,

thanks for your fast reply! Indeed, the reproduction is drawn from a larger project but this should not be the problem. We forgot to mention that the first `npm run build` shows no error and the build finishes. However, if you do `npm run build` a second (or even more) time, the error somehow occurs. 

Thanks a ton!

**Comment by alicewriteswrongs** [comment]
@jnessel thanks for providing some more info on where you're running into the issue. I've just tried again with the reproduction case provided and I can't seem to get the problem to show up - I've run `npm run build` about 10 times in a row in the repo with no errors.

Is it possible there's some particularity about your environment which could be influencing it? It looks based on your screenshots like you're using a windows machine - do you have access to a linux computer or VM you could use to see if it's a windows-specific issue, for instances?

Hope we can get to the bottom of this!

**Comment by insiders-technologies** [comment]
Hello @alicewriteswrongs,
Sorry for the misunderstanding, it seems we had not pushed the latest changes.
We were able to replicate the error on another Windows machine, so the error should occur if you pull the latest changes. 

We noticed another irregularity, if the tag of the component 'my-toggle' is changed to 'my-label', the error will not occur. Somehow, with the tag 'my-toggle', it occurs.

I hope that you can replicate the error and I'm sorry for these circumstances.
Thank you for your patience.

**Comment by alicewriteswrongs** [comment]
@insiders-technologies thanks for updating the repo, I'm now able to reproduce the issue. I'm not sure precisely what the problem is, but thank you for pointing out that renaming the tag for the component changes things - I suspect there is some sort of alphabetical sorting dependency which is causing the imports to be handled in an inconsistent way.

I am going to label this so we can ingest it into our internal backlog and prioritize it.

In the meantime, as you already figured out renaming the component might be an acceptable workaround to circumvent the issue, although I recognize that it is not a long-term solution. Imports into `components.d.ts` should not be dependent on components' tag names, so this is something we're going to want to fix.

Thank you again for reporting, and for helping get to the bottom of this!
