### ISSUE TITLE
Broken build when CSS contains escape characters

### ISSUE THREAD

**Issue by tungd** [ionic-team/stencil#404]
**Stencil version:**

```
 @stencil/core@0.1.1-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

If any of the CSS files in `styleUrls` contains escape characters (i.e `"\f104"`, commonly used in icon fonts such as FontAwesome) the build break, with various erroneous behavior such as some style are not applied, or just blank page (the components have effective  style `visibility:hidden`.

I'm able to work around this by manually double escape (replace `"\f104"` with `"\\f104"`). Another work around I can think of is to build the styles separately and include them in `index.html`, with the cost of livereload no longer works.

**Comment by ansarizafar** [comment]
I am also facing the same issue with TailwindCSS. Hover styles are not available.

**Comment by jgw96** [comment]
Hey all! Investigating this, but it looks like this is actually a Sass thing. Will update here once I figure it out.

**Comment by jgw96** [comment]
Alright, did some more research. So after looking at https://github.com/sass/sass/issues/659 and then seeing that fontawesome has special instructions for people using sass (so as to avoid this issue), it definitely looks like this is a sass thing and not a Stencil specific issue. Good thing is that post 1.0 one of our goals is to make sass optional and make plain css an option, which would solve this issue. Because this is a sass issue and not Stencil specific I am going to close this issue for now. Thanks for using Stencil!
