### ISSUE TITLE
bug: tsconfig alias path transpilation regressed in 3.4.1

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/stencil#4550]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.4.1

### Current Behavior

TSConfig alias paths such as `@utils/helper` are not being transpiled to their relative paths (i.e. `../../utils/helpers`) on build, resulting in warning when consuming the `collection` target:

```
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/helpers' is imported by
           node_modules/@ionic/core/dist/collection/components/datetime-button/datetime-button.js, but could not be
           resolved – treating it as an external dependency
```

### Expected Behavior

I expect there to be no warning.

### System Info

```
     System: node 16.19.0
    Platform: darwin (22.2.0)
   CPU Model: Apple M1 Pro (8 cpus)
    Compiler: /Users/liamdebeasi/Ionic/ionic/core/node_modules/@stencil/core/compiler/stencil.js
       Build: 1687785553
     Stencil: 3.4.1 🐨
  TypeScript: 5.0.4
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.18.1
```

### Steps to Reproduce

1. Clone https://github.com/ionic-team/ionic-framework
2. In `core` run `npm install && npm run build`.
3. Open `core/dist/collection/components/datetime-button/datetime-button.js`. Observe that `@utils/helper` is still an import path at the top.
4. Install Stencil 3.4.0 using `npm install @stencil/core@3.4.0`.
5. Run `npm run build`.
6. Open `core/dist/collection/components/datetime-button/datetime-button.js`. Observe that the correct relative path is specified.

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

### Additional Information

- This appears to be fixed in Stencil 4.0.0, however it would be great to get that fixe backported since 3.4.1 is the latest version of 3.x.

**Comment by tanner-reits** [comment]
@liamdebeasi So, this isn't technically a regression as the behavior in 3.4.1 is how this should behave. The problem is that the root-level `transformAliasedImportPaths` doesn't actually control the transformations in `dist` (and subsequently `dist-collection` that gets synthetically injected as an addition output target). For paths in this output to get transformed, you'll need to have the following in the `dist` target config:
```ts
{
  type: 'dist',
  transformAliasedImportPathsInCollection: true,
  ...
}
```

We agree it's not ideal to have two flags controlling similar behavior. The plan (as of now) is that the output target specific flag will be removed in the next major release of Stencil and all path transformations will be determined by the root-level `transformAliasedImportPaths` flag.

The reason this is "fixed" in v4 is because `transformAliasedImportPaths` and `transformAliasedImportPathsInCollection` both now default to `true`.
