### ISSUE TITLE
bug: defineCustomElements return type is wrong

### ISSUE THREAD

**Issue by andrew9994** [ionic-team/stencil#4589]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.1

### Current Behavior

Currently the return type of `defineCustomElements` is defined as a `Promise<void>` on [this](https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/output-lazy-loader.ts#L88C25-L88C45) line in the output-lazy-loader,
but the promise got removed in [this](https://github.com/ionic-team/stencil/commit/687592004e26be8a4ff3735b5dd7854440ff03aa#diff-aa243938e993487e7a3d8d8361f892f44009528eb48f7cf8028ab69b3ae3446bL193) commit. 

### Expected Behavior

The return value of `defineCustomElements` should be typed correctly. However, I am not sure whether this change should be marked as a breaking change.

### Steps to Reproduce

Import `defineCustomElements` from the loader of a package and try to do something after the promise gets resolved.

```
import { defineCustomElements } from 'stencil-package/loader';

defineCustomElements().then(() => {
  console.log('elements defined');
})
```

### Code Reproduction URL

n/a

**Comment by alicewriteswrongs** [comment]
@andrew9994 thanks for reporting, I was just able to confirm that this is an issue by putting together a quick reproduction here (https://github.com/alicewriteswrongs/stencil-custom-elements-repro)

In the future when reporting issues if you have time to put together something along those lines it greatly helps us in diagnosing problems!

The fix is straightforward here so I'm going to get going on it. Thanks again for filing this!

**Comment by andrew9994** [comment]
Thanks @alicewriteswrongs for jumping on this so quickly 😊 and sorry for not creating a repro repo, will do it next time.
