### ISSUE TITLE
bug: Stencil Wrapper components for Vue not usable with Vite

### ISSUE THREAD

**Issue by verena-ifx** [ionic-team/stencil#4598]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.0.0

### Current Behavior

I found this [issue ](https://github.com/ionic-team/stencil/issues/3961), but sadly it was closed.
I am expierencing the same issue.
I have a core library and two wrapper libraries for vue and react. Build and deployment works fine and testing them locally using npm link as well. I have a similar setup as here [Ionic example project](https://github.com/ionic-team/stencil-ds-output-targets/tree/main/packages/example-project/component-library-vue)

Once I deploy my vue-library to npm and try to use it in an example application with Vue3 and Vite, I get the following errors: Failed to fetch dynamically imported module: my-component. The same error occurs when using React + Vite.

I have set enableImportInjection to true in my stencil.config.js, but still the same error. 

### Expected Behavior

should work as described in the official documentation

### Steps to Reproduce

I simply followed the instructions of the Stencil documentation and now added the extras - enableImportInjection: true to my stencil.config

### Code Reproduction URL

https://github.com/Infineon/infineon-design-system-stencil 
=> examples/wrapper-components/vue-javascript/ => npm i @infineon/infineon-design-system-vue => npm run dev

**Comment by tanner-reits** [comment]
Hi @verena-ifx 👋 

I was able to reproduce the issue you were seeing around the error for reading `isProxied` of `undefined` in a local project built using the [Vue wrapper docs](https://stenciljs.com/docs/vue) and using `npm pack` instead of package linking. However, after setting `enabledImportInjection: true` and rebuilding/packing everything the error went away.

Just for clarity's sake, can you confirm that you rebuilt both the Stencil library and Vue library before re-publishing/re-packing and testing in the consuming Vue app?

If so, I'm happy to dig a little deeper and check out the project you linked in the reproduction. Just let me know!

**Comment by verena-ifx** [comment]
Hi @tanner-reits Thanks for getting back to me! I just did another test, and went over my github-actions files again. And I noticed I had the step "cache dependencies" which used the package-lock.json and possibly some old versions that did not have the "enableImportInjection" flag set to true yet. It is working now. I will close this ticket :) Have a nice day!
