### ISSUE TITLE
bug: error installing dependencies for new projects

### ISSUE THREAD

**Issue by ayangweb** [ionic-team/stencil#4634]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

^4.0.0

### Current Behavior

After creating a brand-new component library project, installing dependencies with `pnpm` reports the following error!

<img width="1413" alt="image" src="https://github.com/ionic-team/stencil/assets/75017711/c1b3450d-1f9d-483c-9b7b-0d30e07fa31f">

### Expected Behavior

How to install dependencies correctly and successfully launch the project!

### Steps to Reproduce

```bash
npm init stencil
```

Select to create a `component` project

```bash
pnpm install
```

### Code Reproduction URL

No link

**Comment by rwaskiewicz** [comment]
Hey @ayangweb 👋 

This is an issue that we see time to time where Puppeteer tries to download Chrome as a part of your `pnpm install` command. Unfortunately, this is not something we're able to handle, as Puppeteer kicks off an effort to install Chrome and _something_ happens to make that fail. In your particular case, it looks like the version of Chrome that Puppeteer wants cannot be found on the NPM registry server

>  Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirrors/114.0.5735.133/mac-arm64/chrome-mac-arm64.zip at /Users/ayang/DownLoads/test-ui/node_modules/.ppm/@puppeteer+browsers@1.4.2/node_modUles/@puppeteer/browsers/lib/cjs/httpUtil.js

Since this is outside of the scope of Stencil, I'm going to close this issue. Thanks again for the bug report!
