### ISSUE TITLE
Duplicated CSS for multiple instances of the same component

### ISSUE THREAD

**Issue by PChiesa** [ionic-team/stencil#465]
**Stencil version:**

```
 @stencil/core@0.2.3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When creating a component with styleUrl defined, If you use multiple instances of the same component and have prerendering on, the resulting html will have multiple copies of the same css inside <head></head>.

**Expected behavior:**

If you have multiples instances of the same component, the common parts(like css), should not be repeated on the resulting html.

**Steps to reproduce:**

Create a component1 with styleUrl filled.
Inside render() of component2, add multiple instances of the previous created component1.
Build the project with prerendering on.

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
We're will be some duplicate css added from prerendering, and from the runtime code, but the prerrendering version won't be fully complete, which wouldn't make it safe to not add the runtime's version. What I mean is, prerendering adds only the actually used css on the prerendered page, and it'll take out any css not used. But during runtime, you might need some of the stuff that may have already been removed. So instead of coming up with a runtime parser that tries to figure out what it does and does not need, it's easiest to just set all the css again, which shouldn't cause any issues. Hope that helps answer this, and thanks for raising the issue.
