### ISSUE TITLE
bug: Cannot run individual unit tests - repeat of earlier issue

### ISSUE THREAD

**Issue by Kwooda** [ionic-team/stencil#4684]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.5

### Current Behavior

This is a repeat of an issue that was fixed in an earlier version: #3276 
I am unable to run individual unit tests. All unit tests are executed.
npm run test is defined as "stencil test --spec --e2e --coverage"
npm run test my-component
should run unit tests only for my-component. Instead, unit tests for all components run.

### Expected Behavior

Only the named unit test should run when specifying an individual component.
npm run test my-component

### System Info

```shell
System: node 16.15.0
    Platform: darwin (22.2.0)
   CPU Model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 cpus)
    Compiler: /Users/tkmafa3/projects/designsystem/kds-web-core/node_modules/@stencil/core/compiler/stencil.js
       Build: 1692031915
     Stencil: 4.0.5 🚣
  TypeScript: 5.0.4
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.19.2
```

### Steps to Reproduce

Try to run an individual unit test.

### Code Reproduction URL

https://github.com/Kwooda/StencilUnitTests

### Additional Information

The reproduction URL above is from the original bug report - it has not been updated to stencil 4.0.5 as of this writing. I will see if I can update it in the interim.

**Comment by Kwooda** [comment]
Reproduction repo has been updated to show the issue in StencilJS 4.0.5

**Comment by alicewriteswrongs** [comment]
Hey @Kwooda, thanks for reporting this and sorry you're still having trouble running a single spec file with Stencil.

I don't think the behavior of this has changed on Stencil's side recently. When you pass commands to `stencil test` they will be passed through to Jest, and in order to pass a filename pattern to Jest it needs to be prepended with `--`. So in your repro I'm able to do something like this:

```sh
npx stencil test --spec --e2e -- my-component
```

note the `--` separating the flags like `--spec` and `--e2e` from the `my-component` filename pattern.

Then if you want to be able to do the same thing with a predefined `test` script in `package.json` (like you have set up) you'll _also_ need a `--` to delineate arguments which should be appended to the command when it's called.

What that means is that if you do something like

```sh
npm run test -- -- my-component
```

then that will result in `npm` running a command like so:

```
stencil test --spec --e2e --coverage -- my-component
```

because when you `npm run test --` everything after the `--` argument will be injected into the command. So it's a bit funny looking, but in your repro case in order to run just the `my-component` tests you should be able to do the following:

```sh
npm run test -- -- my-component
```
