### ISSUE TITLE
bug: The types folder will not be packaged

### ISSUE THREAD

**Issue by wabi-habi** [ionic-team/stencil#4716]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.2

### Current Behavior

<img width="1738" alt="image" src="https://github.com/ionic-team/stencil/assets/99811051/e9829506-0997-4a4d-ab6c-429e664ccfef">

Because of the `title` field within the component, the packaging reports `warn`, which causes the `types` folder to not be packaged correctly! In case I have to use `title`, I would like to ask how to solve this problem? Or how to turn off `warn` completely?

### Expected Behavior

Why is it not packed? What went wrong?

### Steps to Reproduce

`pnpm build` is executed multiple times, occasionally packaged, occasionally not!

### Code Reproduction URL

https://github.com/ayangweb/stencil-test

**Comment by rwaskiewicz** [comment]
Hey @wabi-habi  👋 

Can you please provide additional steps to reproduce this error? The reproduction repo has react/vue code wrapper code in it as well, which also makes it a little tricky to debug this error. Ideally, a reproduction case should include it's own repository with the least amount of code needed in order to reproduce the issue and the steps needed to reproduce the error. At present, the current steps are a little too vague for us to look into this. If all this code is necessary, please let us know. Thanks!

**Comment by wabi-habi** [comment]
You can follow along with the video using `pnpm build:core`

https://github.com/ionic-team/stencil/assets/99811051/6b19a2f3-ef09-4f00-95b3-8040a9547efb
