### ISSUE TITLE
New builds always display my first (old) stencil app on port 3333

### ISSUE THREAD

**Issue by kristianmandrup** [ionic-team/stencil#515]
Tried shutting down my laptop terminating all processes. 

Then created two new apps in new folders using starter kit, clone `--depth 1`. 
Each time when I run `npm start` my browser is launched with the first StencilJS app I created (wheel of fortune). 

How can this be happening? So strange...

**Comment by davidchristie** [comment]
This could be due to the service worker Stencil apps install in the browser (for production builds only).

I.e. if you run `npm run build` and then `npm run serve`, the production build will be served on `localhost:3333` and a service worker will be installed. This will continue to serve up a cached version of your app even after you have terminated the server.

You can remove service workers in the Application tab of Chrome devtools.

**Comment by kristianmandrup** [comment]
Thanks. I'm sure that is the reason. Would be nice if this was documented on the Stencil docs. Awaiting a nice update of docs for 1.0 release :)
