### ISSUE TITLE
bug: scopedCSS default slot content bad placement after using textContent

### ISSUE THREAD

**Issue by oscargm** [ionic-team/stencil#5267]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.10.0

### Current Behavior

After updating the default slot using textContent on the host element, the new content is placed together the old one, just before it

### Expected Behavior

Having this initial markup

```html
<scoped-list-item
  id="scoped"
  class="sc-scoped-list-item-h sc-scoped-list-item-s hydrated"
  >
  <!---->
  <li class="sc-scoped-list-item">
    <div class="list-wrapper sc-scoped-list-item sc-scoped-list-item-s">
      <span slot="prefix">&gt;</span>
      <span>Scoped list item 1</span>
      <span slot="suffix">X</span>
    </div>
  </li>
</scoped-list-item>
```
Where Scoped list item is the content provided as text in the default slot.

after performing 

```js
document.querySelector('#scoped').textContent = 'Whatever'
```

It should render:

```html
<scoped-list-item
  id="scoped"
  class="sc-scoped-list-item-h sc-scoped-list-item-s hydrated"
  >
  <!---->
  <li class="sc-scoped-list-item">
    <div class="list-wrapper sc-scoped-list-item sc-scoped-list-item-s">
      <span slot="prefix">&gt;</span>
      <span>Whatever</span>
      <span slot="suffix">X</span>
    </div>
  </li>
</scoped-list-item>
```

Instead it renders:

```html
<scoped-list-item
  id="scoped"
  class="sc-scoped-list-item-h sc-scoped-list-item-s hydrated"
  >
  <!---->
  <li class="sc-scoped-list-item">
    <div class="list-wrapper sc-scoped-list-item sc-scoped-list-item-s">
      <span slot="prefix">&gt;</span>
      Whatever
      <span>Scoped list item 1</span>
      <span slot="suffix">X</span>
    </div>
  </li>
</scoped-list-item>
```

### System Info

```shell
npx stencil info

      System: node 18.19.0
    Platform: linux (5.15.0-91-generic)
   CPU Model: 12th Gen Intel(R) Core(TM) i7-1260P (16 cpus)
    Compiler: /home/users/garciamo/roche/repositories/garciamo/stencil-scoped/node_modules/@stencil/core/compiler/stencil.js
       Build: 1705333241
     Stencil: 4.10.0 🍪
  TypeScript: 5.3.3
      Rollup: 2.42.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.26.0
```

### Steps to Reproduce

Clone [this repo](https://github.com/oscargm/stencil-scopedcss-slot-repro) run npm start and play with the demo.

Button also updates suffix named slot (which works fine btw)

### Code Reproduction URL

https://github.com/oscargm/stencil-scopedcss-slot-repro

**Comment by tanner-reits** [comment]
@oscargm We introduced a new flag in Stencil v4.10, [`experimentalScopedSlotChanges`](https://stenciljs.com/docs/config-extras#experimentalscopedslotchanges), that updates some of Stencil's behavior related to slots outside the shadow DOM to more closely match the shadow DOM implementation. One of those changes is related to `textContent`. I enabled the flag in your repro and that makes it so the result for both the shadow and scoped components are the same. Does this solve your issue?

If you were using a previous release of Stencil with the `experimentalSlotChanges` flag, the `textContent` change was initially behind this flag, but we needed to add a new flag since changes like that didn't really fit within `experimentalSlotChanges`.

Let me know if that unblocks you or if I can do anything else!

**Comment by tanner-reits** [comment]
@oscargm Took a look at the updated example and tried out a couple different things. 

I think `textContent` is working as expected. If you setup the same examples using the `shadow-list-item`, the markup results in (essentially) the same thing. In both cases, the `span` element is not retained.

As for `innerHtml`, we don't currently patch that method for `scoped` Stencil components, so there may be some discrepancies between scoped and shadow components.

We can treat this as a request for us to patch `innerHtml` to match the Shadow DOM implementation if that would help anything. Otherwise, I believe this is working as expected.

**Comment by oscargm** [comment]
Yes, my bad, I did some comparisons with native elements and looks like they're behaving correctly.
Sorry for the time and confusion.
I believe we can close this issue.
