### ISSUE TITLE
Unable to use global attributes normally due to ... typescript?

### ISSUE THREAD

**Issue by CH-RhyMoore** [ionic-team/stencil#530]
**Stencil version:**

```
 @stencil/core@0.4.0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**I realize this "bug" is most likely not directly related to Stencil, but I didn't know a better place to post it given that I don't typically use JSX or TypeScript.**

**Current behavior:**

Clone https://github.com/ionic-team/stencil-component-starter
Begin editing template and use an id attribute on a slot in Stencil's TypeScript+JSX setup

When building, get an error I presume is from some TypeScript definition of which attributes are valid for use on a slot.

```
[ ERROR ]  typescript: src/components/my-component/my-component.tsx, line: 19
           Property 'id' does not exist on type 'SlotAttributes'. 
```

**Expected behavior:**

This is unexpected because there are some attributes that are "global" and are valid on any element. My assumption would be that these should be allowed, so that I am able to use id on slot when using Stencil, just like I can when not using Stencil.

**Steps to reproduce:**

**Related code:**

```tsx
render() {
  return (
    <slot id="default">
    </slot>
  );
}
```

**Other information:**

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element

**Comment by Aaron-Sterling** [comment]
If you post your tsx file on the Ionic forum, I'll answer you there.

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! Since this is more of a support question than an issue with Stencil id recommend you post about it in our Slack channel. You can join here https://stencil-worldwide.herokuapp.com/. Thanks for using Stencil!

**Comment by morewry** [comment]
This isn't a great experience for me as a user. First, I really don't view this as a support request, and if it were... Yuck, having to create new accounts elsewhere? Granted, I thought it was perhaps not _Stencil's_ bug, but it is and remains indisputably a bug. However, it's looking more and more like Stencil's bug to me.

This is current understanding. For built-in HTML elements to be used in JSX, those elements have to be implemented in some additional JSX-related fashion. I presume that this typically involves defining a schema or interface or something along those lines that reproduces the semantics of the built-in HTML elements.

However, the implementation for `slot` doesn't accurately reproduce the real HTML element, so a use of slot that is valid HTML is not valid JSX in Stencil. It throws an error. I know that this usage is valid because of the HTML specification. You can verify that using these sources I previously provided:

https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

Originally I thought this implementation might not be specific to Stencil. But it is. Observe,

### `@stencil/core/dist/declarations/jsx.d.ts`

```typescript
declare global  {
    namespace JSX {
        interface IntrinsicElements {
            slot: JSXElements.SlotAttributes;
        }
    }
    namespace JSXElements {
        interface SlotAttributes {
            name?: string;
        }
        interface HTMLAttributes extends DOMAttributes {
            id?: string;
            title?: string;
        }
    }
}
```

See how that set of attributes for slot doesn't extend anything and only lists `name`? It's supposed to also have all of these,

```
accesskey
autocapitalize
contenteditable
dir
draggable
hidden
inputmode
is
itemid
itemprop
itemref
itemscope
itemtype
lang
nonce
spellcheck
style
tabindex
title
translate
```

As you might imagine, I'm not looking to work around that, I'm looking to report it. I'm not even all that interested in getting a reply to **me** specifically, especially in a place no one else with a similar issue can find it later. It's not a big issue for me--I'm only using Stencil for the purpose of comparing it to other tools for authoring web components--so I was only reporting this to help out.

So you can fix it or you can ignore it, your call. But you can't call it a support request.

**Comment by dwieeb** [comment]
Yes, this is a bug in Stencil JSX definitions: https://github.com/ionic-team/stencil/blob/d462b7f430765748a44f9c6c73efdf94521e135c/src/declarations/jsx.ts#L12

Our [docs on slots](https://stenciljs.com/docs/templating/#slots) link to the HTML element [`slot`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot), which allows global attributes.

This needs to be looked at by a Stencil dev.

Thank you for your thoroughness @morewry and thank you for taking the time to report the issue.

**Comment by jthoms1** [comment]
This is a unique situation.  Slot is not always an actual dom node.
If you have shadowdom set as true on your component then yes the slot element is created and used.
But if shadowdom is not set then slot is just a placeholder in memory that we use for setting the location of where a children should be added.

I consider this a documentation issue and a types issue. We can add the types but we also need to document what the slot is.

**Comment by adamdbradley** [comment]
@jthoms1 is correct and the `<slot>` element is unique in this situation, especially when it is being polyfilled to work on older browsers attempting to act like native shadow dom. Because of this the slot implementation has limitation, and cannot have dynamic changes like it's native implementation. This is a documentation issue and we need to update our slot polyfill limitations. Thanks.
