### ISSUE TITLE
getting "invalid @Listen prefix" when attempting to listen on events from custom components

### ISSUE THREAD

**Issue by stevefuzzy** [ionic-team/stencil#531]
**Stencil version:**

```
 @stencil/core@0.5.0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

when qualifying an event (.e.g myEvent) with its custom component (e.g. app-profile) in a Listen statement, compile fails with the error:
```
    invalid @Listen prefix "app-profile" for "app-profile:myEvent"
```
Removing the app-profile prefix results in a clean compile, but this is not according to the docs.
The only acceptable prefix seem to be  'body'.

**Expected behavior:**

It should compile

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post a simple repo we could use to reproduce this?

**Comment by UserGalileo** [comment]
Hi everybody, actually this was pointed out in the last issue I opened which was closed after 2 months with a generic reply which didn’t solve the problem.

I also tried to reach you via Slack some time ago but got no answer.
I really don’t want to sound polemic, I appreciate your work and the ideas behind Stencil, but it seems to me that some issues are handled just like if you didn’t want to see them.

This is a common issue that wouldn’t really need a repo to be tested out, you just need to write a Listen decorator as explained. If it’s a problem which relates to the OS, I can tell you that I tested it on multiple Windows PCs, but it would be strange.

This kind of thing is why I’m worrying about using Stencil (in the future) for real projects, which also makes (and made) me doubt about Ionic (and I know they’re different projects).

Please take this words as from one of your fans who looks forward for a great and interesting project :)

PS. Since my issue pointed out a pretty essential enhancement and was closed without a reason, I would ask you to reopen it, thanks!

**Comment by stevefuzzy** [comment]
Hi @jgw96 , as UserGalileo pointed out, there should be no need to post a repo for this.  The bug report is explicit: simply use the Listen decorator on a qualified event.  If you tell me you can't reproduce it, then I'd understand the need to post a repo and will gladly do so. I'm running on Windows 7 64bit, if that matters.
Thanks for a great product.  Please keep it up!

**Comment by jgw96** [comment]
Hello all! Sorry about my quick reply from earlier, after re-reading this issue it is simple to reproduce. Ill figure out whats going on here.

**Comment by UserGalileo** [comment]
Thanks, also #323 is the other issue I was talking about before.

**Comment by silentHoo** [comment]
I've the same problem.

**Comment by jgw96** [comment]
Hello all! So we've discussed this issue and this is actually correct behavior, although it's not explicitly documented ( which I will fix ). The only valid prefixes are `child`, `parent`, `body`, `document` and `window`. Now, let me go through each use case here: First, if you are emitting an event from a component and want to listen to that event in another component you do not need to use any prefix, you can just listen for the name of the event that you emit. So if I emitted an event from a component called `myEvent` I would just use `@Listen('myEvent')` to listen to that event from another component.  For `button:click`, you don't actually need to use the `listen` decorator at all. To run a method when a user clicks a button in your app you can use `onClick` on the button itself just like you would in Preact/React https://github.com/jgw96/stencil-beer/blob/949639c3ddc8d4c5a5cfac7916f25f827682af72/src/components/beer-item/beer-item.tsx#L124. Thanks everyone for using Stencil!

**Comment by UserGalileo** [comment]
Actually, I don’t understand how this can be the correct behavior when everywhere else it was stated to work.
I’m not saying things should work well in beta phase, absolutely, but it’s different when things are advised (how could you advise without even trying it once?) or issues are closed proposing the wrong solution?
This gives even more value to #323, which not only was closed telling me the wrong answer, but actually asked for something more precise (and missing), call it an enhancement, a bug, whatever, but the container component, at the moment, cannot orchestrate the behavior of its children properly with the current tools.

Thanks, and good work to you all :)
