### ISSUE TITLE
bug: watch not recognizing every change in css files

### ISSUE THREAD

**Issue by danyball** [ionic-team/stencil#5371]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.12.2

### Current Behavior

Not every change in a css file will trigger the watcher. 

I can just reproduce this issue in the component-starter repo with the characters ";" or " " (space). But imagine the situation on my machine: Regardless of the char the watcher is not triggered. This is annoying.

### Expected Behavior

Every change, regardless of the character which is changed, should trigger the watcher.

### System Info

```shell
System: node 18.19.0
    Platform: darwin (23.2.0)
   CPU Model: Apple M1 Max (10 cpus)
    Compiler: /Users/xxxxx/stencil-component-starter/node_modules/@stencil/core/compiler/stencil.js
       Build: 1707755243
     Stencil: 4.12.2 🎯
  TypeScript: 5.3.3
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.27.0
```

### Steps to Reproduce

1. checkout reproducer repo
2. `npm run start`
3. open `my-component.css`
4. add ";" to line 3 (background:red;) and safe it
5. repeat step 4 multiple times --> watch the console where the watcher is running: watcher is not triggered after each 5-6 times

### Code Reproduction URL

https://github.com/danyball/stencil-no-reload.git

**Comment by rwaskiewicz** [comment]
Hey @danyball 

I was unable to reproduce this locally on my machine with the provided reproduction case. In the video below, I tried adding multiple semicolons and spaces, but on every save, the watcher fired for me. Please note that my save action is explicit here (I hit "CMD+s" to save, rather than having an autosave), so when I enter multiple space characters in quick succession, there is no save action occurring/no reload triggered as a result.

https://github.com/ionic-team/stencil/assets/1930213/bc88b363-6489-4ac5-acb3-03eb05cb3f21

Is there anything I'm missing here?
