### ISSUE TITLE
Shadow Components in IE 11 issue with el.shadowRoot

### ISSUE THREAD

**Issue by jagreehal** [ionic-team/stencil#547]
**Stencil version:**
```
 @stencil/core@0.5.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behaviour:**
I recreated Eric Bidelmans' Fancy Tabs demo but shadow components don't behave in IE 11 (Windows 7) as other browsers. I think the bug is in evaluating

```javascript
this.el.shadowRoot.querySelector('slot[name="title"]')
```

**Expected behavior:**
Running the demo in other browsers works as expected.

**Steps to reproduce:**
See https://jagreehal.github.io/fancy-tabs-stencil-demo/. The repo is https://github.com/jagreehal/fancy-tabs-stencil-demo

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I can not reproduce this with a simple example but I am going to pull your repo down to see if I'm missing something.

**Comment by jgw96** [comment]
Alright @jagreehal , after looking into this further this is not working because we do not create a "fake" slot element in IE11 when we emulate shadow dom. We discussed doing this but decided that it would cause more issues and complexity than it would solve. If its crucial that this demo works in IE11 I would recommend changing your selector to just select elements that have that `name=title` attribute. That will work in IE and new browsers. Thanks for using Stencil!
