### ISSUE TITLE
feat:  Solidjs output adapter

### ISSUE THREAD

**Issue by phy-lei** [ionic-team/stencil#5657]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

I hold Stencil in high regard, and currently, while working with Solidjs, I find myself utilizing web components previously authored using Stencil. It would be most beneficial to have an adapter specifically tailored for Solidjs to facilitate seamless integration.

### Describe the Use Case

A setup configuration mirroring that employed by the 'react-output-target' package

**Comment by christian-bromann** [comment]
@phy-lei thanks for filing the issue.

We currently have not planned to implement a SolidJS output adapter due to conflicting priorities. We recommend however to take a look at the [PublicUI maintained](https://www.npmjs.com/package/@public-ui/stencil-solid-output-target) output adapter for Stencil which has one for SolidJS as well.

I will go ahead and close the issue as there is nothing I can do at the moment except pointing to the recommended package for using Stencil with SolidJS. Let me know if you have any further questions. Thanks!
