### ISSUE TITLE
Don't use passive event listeners for normal DOM events

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil#58]
Many DOM events will need to be prevent defaulted, for example clicks and form submissions. Right now it seems that all events are being sent as passive, so you can't do things like this:

```javascript
  handleClick(e) {
    e.preventDefault();
  }

  render() {
    return (
        <a href={this.url} onClick={this.handleClick.bind(this)}>
          <slot></slot>
        </a>
      )
    }
  }
```

Throws this error:

<img width="1131" alt="screen shot 2017-07-20 at 3 52 02 pm" src="https://user-images.githubusercontent.com/11214/28438321-654ef09c-6d63-11e7-9255-0488a364a464.png">

**Comment by gamebox** [comment]
I actually wonder if this has to do with behavior that I'm seeing with building a complex form that has buttons that toggle sub-forms.  I've noticed that no matter what handler you declare, they cause the host component to re-render, unless you preventDefault().  Seems like that would not be expected behavior.  Does this warrant a new issue for investigation?
