### ISSUE TITLE
Style missing in header with scoped css 

### ISSUE THREAD

**Issue by sebastien-yoobic** [ionic-team/stencil#589]
**Stencil version:**

```
 @stencil/core@<version> 
```
`@stencil/core@0.6.16`

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Style of component missing in the header of the html file 

Instead of the style for scoped attributes I have this:
`<style>/**style-placeholder:yoo-modal:**/</style>`

**Expected behavior:**

The style for scoped attributes is present.

**Steps to reproduce:**

I  created a repo which reproduces the bug here : https://github.com/sebastien-yoobic/stencil-style-bug 

**Related code:**

**Other information:**

The bug only appear if I reuse the modal component in an other component.

```tsx

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  scoped: true
})
export class MyComponent {

  render() {
    return (
      <div>
        <my-modal title="Modal"></my-modal> // Bug
         // No bug without the previous line 
      </div>
    );
  }
}

```

Scoped attributes are presents in the html element in the DOM. Only the style in the header is missing. 

Ask me any question if you need more informations.

Thanks,

**Comment by sebastien-yoobic** [comment]
This seems to be related with the fact that my component is used inside an other component with import. 

If I delete the import and the generateModal method, the bug is not happening.

This is the code of th other component. 

```tsx
import { Component, Element, State, Method } from '@stencil/core';
import { ModalEntry, setModalProps } from '../my-modal/my-modal';

@Component({
    tag: 'my-modal-controller',
    styleUrl: 'my-modal-controller.scss',
    scoped: true
})
export class ModalControllerComponent {

    @Element() el: HTMLElement;

    @State() element: HTMLElement = document.createElement('my-modal');

    @Method()
    generateModal(props: ModalEntry) {
        let m = document.createElement('my-modal');
        m = setModalProps(m, props);
        this.element = m;
    }

    render() {
        return (
            <div></div>
        );

    }
}
```

**Comment by sebastien-yoobic** [comment]
I was able to fix the missing style problem by creating a new file for the ModalEnrty and setModalProps. This way the there is no more import in a component file from an other component file. 
However, I am not sure that the `<style>/**style-placeholder:yoo-modal:**/</style>` in the header is the desired behavior

**Comment by jgw96** [comment]
Hey @sebastien-yoobic , so this could probably be documented better on our part. With web components, you normally do not want to try to import something from another component. Even in something like react, you normally don't import methods from a component into another component. Those methods you want to import and use would normally be in separate files (as you settled on here). The missing style issue happening here was caused by importing one component into another component. Doing that messed up Stencil's static analysis of it and could not find the css to insert in that style tag. This is a normal thing that I would expect to happen in a case where a component cannot be compiled correctly. Thanks for using Stencil!
