### ISSUE TITLE
Edge bug with shadow dom components

### ISSUE THREAD

**Issue by jagreehal** [ionic-team/stencil#664]
**Stencil version:**
 @stencil/core@0.7.6

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Shadow component style can be overridden in Edge

**Expected behavior:**
Shadow dom styles should not be affected

**Steps to reproduce:**

https://jagreehal.github.io/stencil-edge-shadow-dom-bug/index.html

github: https://github.com/jagreehal/stencil-edge-shadow-dom-bug

**Comment by jgw96** [comment]
@jagreehal so this is not working because even though `.box` in the component itself is technically more specific, `!important` still wins. In native shadow dom browsers, that global css selector never even makes it into the shadow root, and therefore never applies. The fix here if you need to use shadow dom and need it to work in edge and IE is to use `!important` in the css inside your component. This could be polyfillable, but it would be very very slow and the polyfill to emulate css specificity to the point of overriding `!important` would be pretty huge (case in point, shady-dom). Thanks for using Stencil!
