### ISSUE TITLE
Support for extending existing HTMLElement

### ISSUE THREAD

**Issue by Javiani** [ionic-team/stencil#704]
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

It would be very nice if we could extend existing html element through the  `is` html property.
Have you considered to support extending html elements in the future?
E.g 
```html
<button is="my-component">My button component</button>
```

**Comment by adamdbradley** [comment]
Thanks for the suggestion, but in the early stages yet, and in order to keep the API small I think we'll hold off on this feature. If it's a highly requested feature we can re-evaluate again later. Thanks for using stencil!

**Comment by ctaepper** [comment]
This feature request is a valid one in my opinion. In fact, this feels like 50% of the greatness of webcomponents: build your own, or customize existing. 

Having a strong angular background, I immediately fell in love with stencil (as with all products from the ionic team). But providing a new technology covering only 1 of 2 main features feels not right. When doing this in native JS, it's close to an one-liner. Does it really blow the stencil API up that much?

Don't get me wrong, I appreciate open source and everything what the ionic team has done in the past,
but closing this issue with a "nope, not doing it" is wrong. At least leave the issue open, so we know this is something that is considered and will be coming in the future. Right now - as much as I want to - I cannot chose stencil for any project, because I have to think, this will always be just 50% done.

**Comment by runarberg** [comment]
Duplicate of #1382?
