### ISSUE TITLE
Fallback content for named slots in Firefox and IE11

### ISSUE THREAD

**Issue by jagreehal** [ionic-team/stencil#706]
@stencil/core@0.7.18

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Fallbacks for named slots aren't working in Firefox or IE

**Expected behavior:**
The polyfill used should support this

**Steps to reproduce:**
See https://github.com/jagreehal/stencil-named-slots or open https://jagreehal.github.io/stencil-named-slots/index.html

**Other information:**
If we choose not to polyfill slot specification we need to document this. I say we as I'm happy to help write the docs to prevent unhappy developers.

**Comment by adamdbradley** [comment]
Yes this should work, so must be a bug which can be fixed up. Thanks for the repo!

**Comment by adamdbradley** [comment]
Try release `0.7.27-1`

**Comment by juanmiguelbesada** [comment]
@adamdbradley I can confirm it's fixed in 0.7.27-1

stencil/core 0.7.18
![captura2](https://user-images.githubusercontent.com/295490/39172798-1fd9c2e2-47a3-11e8-9269-6e722f77ee33.JPG)

stencil/core 0.7.27-1
![captura](https://user-images.githubusercontent.com/295490/39172799-1ffb0a9c-47a3-11e8-975e-ccda32d06459.JPG)

**Comment by jagreehal** [comment]
Looks good to me! https://jagreehal.github.io/stencil-named-slots/index.html :shipit:

**Comment by adamdbradley** [comment]
thanks everyone!
