### ISSUE TITLE
Elements rendered outside the shadow root

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil#727]
**Stencil version:**

```
@stencil/core@0.7.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Elements seem to be rendered outside the shadow root.

**Expected behavior:**
All elements in the template are rendered inside the shadow root

**Steps to reproduce:**

I've reproduced the issue here: https://github.com/dimi-nk/stencil-show-render-error
- Clone project & `npm install`
- Run with `npm start`
- Read the note at the bottom

These are the generated elements after navigating back to page 1.
![image](https://user-images.githubusercontent.com/2273840/38685769-9916518a-3e6a-11e8-8dcf-2bc2558d9ea9.png)

![image](https://user-images.githubusercontent.com/2273840/38685791-a39cdaac-3e6a-11e8-8edd-a1bd3a23f330.png)

**Other information:**

**Comment by dimi-nk** [comment]
It might be the way I render the child components:
```jsx
 // this fails
  render() {
    return this.values.map(value => {
      return <div>{value.value}</div>;
    });
  }

 // this works
  render2() {
    const a = this.values.map(value => {
      return <div>{value.value}</div>;
    });
    return (<main>{a}</main>);
  }
```

**Comment by jgw96** [comment]
Hello! Thanks for using Stencil. I am not able to reproduce this issue with the latest version of Stencil. I would recommend updating to 0.7.20.

**Comment by dimi-nk** [comment]
I can still see this issue after updating

**Comment by doliG** [comment]
Hello @dimi-nk ,

I think it's because you try to return an array of JSX element in your first example.

In my experience, when you try to return an array of JSX elements with React, you get the following error: `Adjacent JSX elements must be wrapped in an enclosing tag`

In your case and because you're not using react, you should try to wrap what you return in another JSX element just like you did in `render2()`.

I think something like this should work:
```jsx
render() {
  return (
    <div>
      {this.values.map(value => <div>{value.value}</div>}
    <div>
  );
}
```

Note that there is no need to use return in an arrow function (except if you find it's better for readability 😉).

I suggest you this readings:
https://reactjs.org/docs/fragments.html
https://codeburst.io/fragment-in-react-1cd69f158910

Let me know if it helps 😊

**Comment by dimi-nk** [comment]
Hey @doliG thanks for the info (I know the arrow fn part 😂 ).

I have a few cases in stencil components where I do this (and it works just fine):

```jsx
return [<div></div>, <div></div>];
```

Any ideas?

**Comment by juanmiguelbesada** [comment]
I still can reproduce this issue in 0.7.24

**Comment by jgw96** [comment]
Hello all! We are currently refactoring slots which should fix this issue. I will give this another test once that is done.
