### ISSUE TITLE
Clear requirement around TypeScript

### ISSUE THREAD

**Issue by thepian** [ionic-team/stencil#761]
**Stencil version:**
```
latest
```

**I'm submitting a:**
[x] documentation issue

**Current behavior:**
The presentation and README talks about components written in TypeScript. It is not clear to which extent writing in ES6 is supported, and will remain so. It seems pretty essential to know for certain that TypeScript will not become a requirement, or that it essentially is.

**Comment by manucorporat** [comment]
@thepian typescript compiler is a core requirement. Stencil uses the compiler API of typescript in order to extract the compiler-time metadata from the TS AST.

In the other hard, typescript as language can be relaxed using custom tsconfig.json, so ES6 (without any explicit types) can work without mayor problem.

Typescript is a superset of JS, that means JS is still valid TS.

**Comment by thepian** [comment]
This doesn't answer the concern at all. Your comment is purely technical, and doesn't say anything about what Stencil is intended to support. You can use the Typescript compiler to reason about ES6, but you're not implying whether it will rely on non-standard notation in the Component source code.

For somebody to seriously consider using Stencil, they would have to accept Typescript as a requirement for Component authoring, or accept needing to fork the project in the future.

I think it is fair to request a clear statement about the minimum requirements of Stencil component source code. Is it ES6 or Typescript? And for that statement to be put in the readme rather than a comment in a closed issue.
