### ISSUE TITLE
Build failing on Typescript error 

### ISSUE THREAD

**Issue by Tonyhliu** [ionic-team/stencil#837]
**Stencil version:**

```
 @stencil/core@<0.9.7>
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
![screen shot 2018-06-04 at 3 34 13 pm](https://user-images.githubusercontent.com/16828863/40945917-a3860a06-680f-11e8-8bcf-df16f1bb20d2.png)

After updating to latest Stencil version, hitting a Typescript error about MouseEvent (which worked
 in the previous stencil core versions). See screenshots below

![screen shot 2018-06-04 at 3 33 40 pm](https://user-images.githubusercontent.com/16828863/40945366-54de2da4-680d-11e8-9f6a-985c436816e1.png)

![screen shot 2018-06-04 at 3 33 25 pm](https://user-images.githubusercontent.com/16828863/40945367-54f60b22-680d-11e8-8b5d-0d4c0389bbf0.png)

**Expected behavior:**
Build to succeed without having to comment the event handler / handler and event (attached on HTML span) out

**Comment by jthoms1** [comment]
'onMouseOut' is a reserved attribute for all HTML Elements that should not be overridden in your own component code.  Instead you should use a different name.  It is likely that this was not being correctly enforced in previous versions of Stencil and now it is.

In this scenario it appears that you are listening to a mouse out event on a span and then reemitting from the parent component.  You would be better served to rename the event because it technically is not a mouseOut event on the component but from an inner child.

The solution would be to change the name of the event that your component is emitting. Thanks!
