### ISSUE TITLE
building a component

### ISSUE THREAD

**Issue by mailok** [ionic-team/stencil#875]
**Stencil version:**

```
 @stencil/core@0.9.1
```

Create a component, but now I want to use it somewhere, I executed the command: **npm run build**, and this is my result: 

![a](https://user-images.githubusercontent.com/3769277/41782934-8f460f66-7609-11e8-9b02-83f4aeb1e1bf.PNG)

I copied **only** the file **st-button.js**, because that's what my component is called.
but when I try to use it, it gives me an error:

![b](https://user-images.githubusercontent.com/3769277/41783149-31aaf49c-760a-11e8-9641-18c2fb387b9b.PNG)

this is my simple HTML:

```
<!DOCTYPE html>
<head>
    <script src="st-button.js"></script> </head>
<body>
    <st-button text="Hola Mundo"></st-button>
</body>
</html>
```

But when I copy the folder **st-button** in the same direction as **st-button.js** works correctly:

![copia a](https://user-images.githubusercontent.com/3769277/41783769-b9c354ea-760b-11e8-84e1-9fe243a122b9.PNG)

![c](https://user-images.githubusercontent.com/3769277/41783619-4c720ac6-760b-11e8-9a1d-102c0894bbf5.PNG)

Why do I need the folder? That makes my component much bigger, I just want to use a simple **.js**
this is not possible?

**Comment by mailok** [comment]
I guess inside the **dist** folder, I'm going to execute the **npm init** command, create my package.json. and publish it, use it in this way, as importing it as a npm package if it should work correctly

**Comment by mailok** [comment]
I tried the above with npm and nothing, still does not work.
I copied the complete **dist** folder into a project made in Angular, and in my main module I imported it and nothing, it still does not work

![captura](https://user-images.githubusercontent.com/3769277/41786816-814fcde2-7614-11e8-8fb9-1335d346c834.PNG)

**Comment by Xiphe** [comment]
In general, when you want to use stencil components in another non-stencil-project you need to run `stencil build` and ensure you have a `www` outputTarget. 
That will create a `www/build/` folder. This folder is what you serve in order to use your component(s) somewhere else. 

Unless you configured another name, the folder will contain a `app.js`. This needs to be loaded in documents using your stencil/web components

```html
<!DOCTYPE html>
<head>
    <script src="/www/build/app.js"></script> </head>
<body>
    <st-button text="Hola Mundo"></st-button>
</body>
</html>
```

The `app.js` is relatively small and does NOT contain the actual components, nor stencil runtime.
It will instead check if the browser has web-component support or needs a polyfill, then load the (polyfilled)stencil runtime and then load the components that are actually used in the dom.

**Comment by Xiphe** [comment]
I'd propose you name your stencil app s.th. like `app` then it would be less confusing.

Because then you would load a `app.js` which then loads `app.[hash].js` (runtime) which then loads `[hash].js` (st-button).

**Comment by mailok** [comment]
@Xiphe  this is my ``` stencil.config.js ```

![a](https://user-images.githubusercontent.com/3769277/41851140-fe29af62-7854-11e8-9e85-c59113fd05c2.PNG)

You tell me the folder ```st-button``` It is my webcomponent then how do I use it?

I have to create an ```index.js```  file that exports all the scripts in the folder?

And if I want to publish it in npm, what file should I put in ```"main": "" ```  in the package.json?

**Comment by Xiphe** [comment]
As i said, it's confusing because you use `st-button` as `namespace` and as a component name.

If you want to consume the component in another project via npm, see [distribution docs](https://stenciljs.com/docs/distribution)

If you want to serve the components so that you can use it as a script, you need to deploy the www/build folder (including the `st-button` folder) to a server and then load `st-button.js` in the document where you want to use the button.

**Comment by mailok** [comment]
@Xiphe What is the difference between the namespace and the name of the component?

What is the difference between www / build folder and dist folder?

**Comment by Xiphe** [comment]
> What is the difference between the namespace and the name of the component?

When you run `stencil build`, you build an **application**, that is capable of rendering web-**components**. The namespace is for the application. The application could also have no default entry and therefore act as a library.
For example twitter bootstrap comes with a lot of components. If you'd build bootstrap with stencil then, "bootstrap" would be the namespace while "button" and "label" would be names of the components.

> What is the difference between www / build folder and dist folder?
[please see docs on output targets](https://stenciljs.com/docs/config#outputTargets)
