### ISSUE TITLE
document data-resources-url

### ISSUE THREAD

**Issue by rbrcurtis** [ionic-team/stencil#903]
**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

I've been playing with stencil and other WC frameworks looking for one that fits my needs. Stencil is pretty awesome but one of my struggles has been with specifying where to load resources from so that lazy loading works correctly (we load js assets from a CDN). I found data-resources-url in your loader code which is perfect, but see that it isn't documented anywhere. 

I'm a bit hesitant to make use of it as I'd consider it "private" unless its documented.

**Comment by jthoms1** [comment]
Hopefully you should not need to use `data-resources-url`.  This is definitely an internal use mechanism.  How are you loading assets other than components?  Do you have some example code so that I could get a better understanding?

**Comment by rbrcurtis** [comment]
We host all our js and css assets on a CDN so our script tags are all pointing to that. We also pull some common libs, such as bootstrap, from public CDNs. So we've got script tags which src several different hostnames. 

What is the preferred method to tell any given stencil WC lib where to do its loading from?

**Comment by jthoms1** [comment]
Ok, so in most cases the resource location can be figured out by stencil but apparently there are some cases where 'data-resources-url' is needed. So with a little more research it turns out that this is not only an internal use mechanism and is just lacking documentation.

So if it works use it.  I will change this issue to a docs issue so we need to document when to make use of this mechanism

**Comment by rbrcurtis** [comment]
Sounds great. Thank you.
