### ISSUE TITLE
Using ionic/core causes parent Ionic project to render double ion-inputs (reopen)

### ISSUE THREAD

**Issue by joonaspi** [ionic-team/stencil#969]
**Stencil version:**

```
@stencil/core@0.10.10
@ionic/core: 4.0.0-beta.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm building a Web Components library using Stencil while importing Ionic/core to utilise many Ionic components & features inside my components. This component library I am then importing in my main Ionic project.

When I started to use ionic/core and ion-inputs within Stencil components in the main Ionic project the ion-inputs are rendered twice when used in the parent Ionic project. Ion-inputs work normally inside the generated Web Components. So Stencil is causing problems to the Ionic project.

This bug is reopened since the original was closed: https://github.com/ionic-team/stencil/issues/845. Note that the issue has been updated with latest Stencil and Ionic.

This is currently a big problem for my client project. If somebody has some pointers where to look I'm happy to spend time fixing this issue.

**Expected behavior:**

In Ionic project the ion-inputs should not be rendered twice if a Stencil made library is being imported

**Steps to reproduce:**

Demo Web Components library using ionic/core: https://github.com/joonaspi/stencil-components-duplicate
Ionic project using above library with the bug in home page: https://github.com/joonaspi/ionic-using-stencil-bug

Detailed instructions can be found from readme file of the above repository.

Remove from index.html head "<script src='assets/mycomponent.js'></script>" to make the Ionic ion-input duplication bug disappear.

<img width="550" alt="41237117-6f0008cc-6d9b-11e8-995d-e3bede843c09" src="https://user-images.githubusercontent.com/3494646/43391661-f488fd44-93f9-11e8-9cdc-7b2302d698ce.png">

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by joonaspi** [comment]
@jthoms1 did you have time to look at this? Reopened this issue from https://github.com/ionic-team/stencil/issues/845

**Comment by joonaspi** [comment]
More detailed how to reproduce instructions added to readme file of: https://github.com/joonaspi/ionic-using-stencil-bug

**Comment by ceziek** [comment]
I have also this problem on my project.
Issue is also present to other components, like select.

@adamdbradley  any update on that ?

**Comment by kgastelum** [comment]
I also have this issue 

![image](https://user-images.githubusercontent.com/2709468/46686505-1e74dc80-cbbe-11e8-83dc-4b32cf3e65cf.png). 

The content for the component is rendered twice
<elynx-radio-button rv-label="item.label" name="rbgrp" rv-value="item.value" class="hydrated" label="Rivets 1"><label class="elynx-radio-button"><span class="elynx-radio"><span class="elynx-radio-mark"></span></span></label><label class="elynx-radio-button"><span class="elynx-radio"><span class="elynx-radio-mark"></span></span>Rivets 1</label></elynx-radio-button>

The render() method in the component is:
render() {

    return (
      <label class="elynx-radio-button" data-checked={this.checked} onClick={(ev: UIEvent) => this.onChange(ev)} >
        <span class="elynx-radio">
          <span class="elynx-radio-mark"></span>
        </span>
        {this.label}
      </label>
    );
  }

this happens in all browsers.  Note: If I set shadow: true then the issue does not happen in Chrome; otherwise, it happens in all browsers.
using @stencil/core v0.13.2

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
